### ISSUE TITLE
update OSM forms

### ISSUE THREAD

**Issue by lucadelu** [geopaparazzi/geopaparazzi#123]
We have to update OSM forms to the new forms system, that permit to modify or remove the point.

**Comment by moovida** [comment]
Luca, what is still necessary to get this working? 
I have your pull request in. You just need a release to test this? 
Or need the tags also to be updated? Not sure where we are here.

**Comment by moovida** [comment]
Since sadly the form support has been dropped due to missing resources, this can be closed as not fixable.
