### ISSUE TITLE
Geopap on OSM wiki

### ISSUE THREAD

**Issue by sabas** [geopaparazzi/geopaparazzi#148]
http://wiki.openstreetmap.org/wiki/Geopaparazzi

Should be made a page like for other apps, perhaps it draws new users..

**Comment by moovida** [comment]
Since sadly the form support has been dropped due to missing resources, this can be closed as not fixable.

**Comment by sabas** [comment]
(comunque continuo ad usarla per i sopralluoghi :-) )

**Comment by moovida** [comment]
@sabas , questo mi fa molto molto piacere. Mi spiace solo che non sia stato possibile costruire un po' meglio la parte OSM. Magari in futuro, noi continuiamo a cercare progetti che possano supportarlo :-)
