### ISSUE TITLE
empty spatialite layers do not show up

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#203]
Hi @mj10777 , it seems that empty spatialite layers do not show up. 
I assume this is due to the fact that something breaks in the bounds calculation. 

But it is absolutely ok to add empty layers, since the next version will be able to create polygons and one will be starting with an empty table.

Where can this behavior be changed? 
Also, is there a way to call a bounds recalculation on a spatialvectortable? This would be necessary when a new polygon is added. Also, what performance impact would such a query have?

**Comment by mj10777** [comment]
Is this still a problem when creating a new Database?

**Comment by moovida** [comment]
Yes, definitely, and we are solving it by adding a small dummy feature to get started.
Maybe at some point this will have a better solution. Right now it is not my priority to invest too much in this. 
I will close this, let's open it up again when the need for it is here.
