### ISSUE TITLE
Branch rasterlite2 doesn't draw all map in differents zooms

### ISSUE THREAD

**Issue by ssppgit** [geopaparazzi/geopaparazzi#217]
Hi!

I am trying to use the branch 'spatialite_rasterlite2' with the database ''1910.berlin_karten.db'' publish by Mark in this link -> https://github.com/geopaparazzi/Spatialite-Tasks-with-Sql-Scripts/wiki/RasterLite2-Index . I am using the coverage '1910.berlin_karten (1873 Berlin Straube Post-Karte) like tile source.

I am seeing that depend of the zoom level, you don't see all the map. For example in this image you can see that in level 13 you see more tiles that in level 12 you don't see. I am reading the code and i don't understand why this happens because the query is correct.

![rasterlite2](https://cloud.githubusercontent.com/assets/4628696/5568200/29f42808-8f55-11e4-9594-ea8b4f8dd472.jpg)

Are there any limitation with rasterlite2? Thanks

**Comment by mj10777** [comment]
This is a Rasterlite2 specific problem and not a geopaparazzi bug, so I will close this.
