### ISSUE TITLE
Compiling 4.1.1

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#226]
Having not updated my system since a pre 4.0 version and seeing the lastest release
* I am attempting to get a local 'master' running and based on that getting a rasterlite2 version working

`git pull origin`  on master
`./gradlew clean`
* gradle is updated

`./gradlew assemble`
* fails:

```java
:geopaparazzimapsforge:compileReleaseJava
/home/mj10777/gnu_source/adt-bundle-linux/geopaparazzi/geopaparazzi.eu/geopaparazzi/geopaparazzimapsforge/src/eu/geopaparazzi/mapsforge/mapsdirmanager/utils/Note.java:39: error: Note is not abstract and does not override abstract method getImageIds() in KmlRepresenter
public class Note implements INote, KmlRepresenter, GpxRepresenter {
       ^
/home/mj10777/gnu_source/adt-bundle-linux/geopaparazzi/geopaparazzi.eu/geopaparazzi/geopaparazzimapsforge/src/eu/geopaparazzi/mapsforge/mapsdirmanager/utils/Note.java:269: error: cannot find symbol
                images = FormUtilities.getImages(section);
                                      ^
  symbol:   method getImages(String)
  location: class FormUtilities
Note: /home/mj10777/gnu_source/adt-bundle-linux/geopaparazzi/geopaparazzi.eu/geopaparazzi/geopaparazzimapsforge/src/eu/geopaparazzi/mapsforge/mapsdirmanager/sourcesview/SourcesTreeListActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
:geopaparazzimapsforge:compileReleaseJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geopaparazzimapsforge:compileReleaseJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by moovida** [comment]
Hi @mj10777 , I followed your path doing a clean and then assemble, but everything worked as expected.

From the errors it looks like some of the classes do not obey to the interfaces, which is quite strange?

Are you working on a merged branch?

**Comment by mj10777** [comment]
I believe (quite a long time ago), soon after 4.0 I updated to 4.0 and it compiled correctly.
* never installed that version, since I use RasterLite2 heavly and had no time to recreate it

Otherwise `master` has remained untouched

**Comment by moovida** [comment]
Aha, so you are working from the RasterLite2 branch... that might be the problem.

Listen, would you mind reminding me how much storage adding rasterlite2 would mean to geopaparazzi?
Now we have about 9.3 megabytes. Am I right that it would get around 18 megabytes with that addition?

**Comment by mj10777** [comment]
Sorry, I did not see your answer.
No at the moment I am compiling the original master, without the R2 Librarys
* this is failing

My intention is, after compiling the presnt master, in recreating the rasterlite2 branch
* there are no code differences
   * only different librarys

With version 3.9.9
* it was about 3 MB difference

**Comment by mj10777** [comment]
Another reason for this is that I would like to update the present drivers in preperation for the next spatialite version
* the present version of spatialite will only support up to 40 connections
   * due to a logic error, these connections were not properly freed
      * so even after a close, the counter did NOT decrease
* also a lot of changes have been made in RasterLite2, which is still in BETA

**Comment by moovida** [comment]
@mj10777 , I wonder if we could create an optional plugin that would add rasterlite capabilities. That would be a great way to go.

**Comment by mj10777** [comment]
On the fly, I cannot say - having no idea about plugins

I would have my doubts about the usability since
* Rasterlite2 is wholy dependent on the spatialite version being used
   * problems will accure with rasterlite2 if the spatialite is an older version

Both are a part of the `libjsqlite` library
* either with or without rasterlite2

---

So the question is:
* can a plugin be developed that serves only as a Database driver?
   * one plugin in for spatialite only
   * one plugin in for spatialite and rasterlite2

Could any application then just `plugin` during run time and use one of these?
* how would a compiler reate to source code where the library is not a part of the project?

If this could be done, it would be very nice
* only the plugin would then have to be updated when a new version comes out
* any application could use it

But if I remember correctly
* Android likes these things to be self contained

**Comment by mj10777** [comment]
I have just recombiled the `libjsqlite` library
* based on todays (20150116) fossil version

```c
wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20150116.libjsqlite.4.2.1.tar.bz2

wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20150116.libjsqlite.R4.2.1.tar.bz2
```
https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_4.2.1.mk

https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_R4.2.1.mk

I cannot test this with the present `geopaparazzi`
* since the master will not compile

**Comment by mj10777** [comment]
Is
mapsforge/mapsdirmanager/utils/Note.java

onsync with your version?
* this is where the error turns up
   * 
```
/mapsdirmanager/utils/Note.java:269: error: cannot find symbol
                images = FormUtilities.getImages(section);
```
Attempted to change to:
 images = FormUtilities.getImageIds(section);

The the following accured:
```
/mapsdirmanager/utils/Note.java:39: error: Note is not abstract and does not override abstract method getImageIds() in KmlRepresenter
public class Note implements INote, KmlRepresenter, GpxRepresenter {
```
I have no idea how to resolve this.

**Comment by mj10777** [comment]
This problem is still open
* even after a `git reset --hard origin/master` it still occurs
   * so I have no idea how to resolve this

**Comment by mj10777** [comment]
Instead of pulling down the zipped version
* I renamed the directory
* re-clonded it
   * copied  'ant.properties' into geopaparazzi/geopaparazzi.app

and it compiled without problems.

**Comment by tghoward** [comment]
Excellent. I'm glad it is compiling now!
Tim
