### ISSUE TITLE
support a default dummy database type

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#237]
it might be nice to have an empty 4326 db ready to use for editing.

**Comment by mj10777** [comment]
Maybe include a small database that has an imported world borders shape file.
which could also serve as a starting point for geometry display.

http://thematicmapping.org/downloads/world_borders.php
result after importing: 12.4 mb

**Comment by moovida** [comment]
done

**Comment by moovida** [comment]
Btw, I have created a db with one single small geometry in it for each type.

I still do not like the fact that if it is lat/long and there are no bounds the map is not visible (it should be the whole world), but I have no time to work on that and also not sure where to do that.
