### ISSUE TITLE
Offer ability to change language from within program

### ISSUE THREAD

**Issue by Evropi** [geopaparazzi/geopaparazzi#241]
The translation may be unsatisfactory, which in my language's case, it most certainly is.

I actually want to help improve it without recompiling the app and I hope [my credentials](https://www.transifex.com/accounts/profile/Evropi/) are to your liking.

I think this feature will be useful for normal users, too (for the reason stated above), or people using other people's devices on an international team.

**Comment by moovida** [comment]
Thanks for this good suggestion and thanks for the translation to greek!

I now added a preference in which you can choose the locale you want to use in the app, regardless of Android's locale.

It will be in the next release.
