### ISSUE TITLE
Unable to see geopackage contents in the Spatialite data list on the map view

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#248]
Hi there

I've downloaded the Geopaparazzi app from the Play market and have tried lots of gpkg files.

I have been unsuccessful at viewing layers from gpkg files in the Spatialite data list on the map view.

The gpkg files I've tried are from here:

http://www.geopackage.org/#sampledata

What am I doing wrong and how do I get this to work?

Any help is appreciated. Thanks.

**Comment by mj10777** [comment]
There is only a minimal support for gpkg, mostly based on a previous specification.

Due to a lack (then) of good samples, only preparations have been made to support the present specification - but not fully implemented.

Retrievment of geometries will then be done using the spatialite api which support the reading to gpkg geometries.

It is unlikely that support will be done for gpkg tiles, which is based on a completely different logic.

So you are doing nothing wrong.

**Comment by surf9** [comment]
Hi

Thank you for your response.

What tools and workflow do you suggest I follow to create a spatialite db that geopaparazzi fully supports?

E.g. should I start with a shape file and use QGIS to export as a spatialite file?

Please let me know.

**Comment by mj10777** [comment]
The following sql script will create a valid spatialite-table
* 'admin_be' 

from the original gpkg table:
* 'administrative'

importing the
* non-geometry data
* converting the gpkg geometry to spatialite geometries

```sql
SELECT DateTime('now'),'importing a gpkg geometry table as a spatialite geometry table';
-- wget http://www.geopackage.org/data/geonames_belgium.gpkg
-- spatialite geonames_belgium.db < geonames_belgium.sql;
---
SELECT DateTime('now'),'CREATEing TABLE admin_be from geonames_belgium.gpkg administrative';
-- ( "geonameid" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT, "feature_code" TEXT, "country_code" TEXT)
CREATE TABLE admin_be
(
 geonameid INTEGER PRIMARY KEY,
 name TEXT DEFAULT '',
 feature_code TEXT DEFAULT '',
 country_code DEFAULT ''
);
-- SELECT * from gpkg_geometry_columns WHERE table_name='administrative'
-- administrative	location	Point	4326	2	2
SELECT AddGeometryColumn('admin_be','location',4326,'POINT','XY');
SELECT CreateSpatialIndex('admin_be','location');
---
SELECT DateTime('now'),'ATTACH DATABASE: geonames_belgium.gpkg';
ATTACH DATABASE "geonames_belgium.gpkg" AS db_import;
---
INSERT INTO admin_be
(
 geonameid,name,feature_code,country_code,location
)
SELECT
 geonameid,name,feature_code,country_code,
 GeomFromGPB(location)
FROM db_import.administrative;
---
SELECT DateTime('now'),'DETACH DATABASE: geonames_belgium.gpkg';
DETACH DATABASE db_import;
---
SELECT DateTime('now'),'Updating Statistics';
SELECT UpdateLayerStatistics('admin_be','location');
---
SELECT DateTime('now'),'geonames_belgium.sql [finished]';
---
```

I have not tested if this is readable in geopaparazzi, but I assume it will be.

**Comment by surf9** [comment]
Thank you. I will give it a go :-)

**Comment by tghoward** [comment]
And if you want to use a GUI to create a spatialite DB, "Spatialite GUI"
has worked well for us:

http://www.gaia-gis.it/gaia-sins/

Just make sure you "update layer statistics" after you import all your
data.
Tim

**Comment by surf9** [comment]
Hi Tim

In Spatialite GUI, I tried "update layer statistics" after importing the shape file at the database level and also some of the tables. I managed to see the feature in the spatial data list this time. However, when switching back to the map view it crashes with the following error message:

APP_VERSION_CODE=68
APP_VERSION_NAME=4.2.3
ANDROID_VERSION=4.4.2
PHONE_MODEL=GT-I9506
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalArgumentException: invalid longitude: 182.99004
at org.mapsforge.core.model.Coordinates.validateLongitude(Coordinates.java:133)
at org.mapsforge.core.model.GeoPoint.validateCoordinates(GeoPoint.java:69)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:104)
at org.mapsforge.core.model.GeoPoint.<init>(GeoPoint.java:94)
at eu.hydrologis.geopaparazzi.maps.overlays.MapsforgePointTransformation.transform(MapsforgePointTransformation.java:37)
at com.vividsolutions.jts.android.ShapeWriter.transformPoint(ShapeWriter.java:386)
at com.vividsolutions.jts.android.ShapeWriter.appendRing(ShapeWriter.java:265)
at com.vividsolutions.jts.android.ShapeWriter.toShape(ShapeWriter.java:235)
at com.vividsolutions.jts.android.ShapeWriter.toShape(ShapeWriter.java:297)
at com.vividsolutions.jts.android.ShapeWriter.toShape(ShapeWriter.java:217)
at eu.hydrologis.geopaparazzi.maps.overlays.GeopaparazziOverlay.drawGeometry(GeopaparazziOverlay.java:922)
at eu.hydrologis.geopaparazzi.maps.overlays.GeopaparazziOverlay.drawFromSpatialite(GeopaparazziOverlay.java:798)
at eu.hydrologis.geopaparazzi.maps.overlays.GeopaparazziOverlay.drawOverlayBitmap(GeopaparazziOverlay.java:439)
at org.mapsforge.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:319)
at org.mapsforge.android.maps.overlay.Overlay.run(Overlay.java:251)

LOGCAT=--------- beginning of /dev/log/main

Is there a specific table I'm supposed to "update layer statistics" on?

**Comment by moovida** [comment]
Two things I would like to highlight:

*  invalid longitude: 182.99004 -> this looks odd. How is it possible that you get a longitude larger than 180?
* consider that a spatialite db is different than a geopackage db. Tim is talking about spatialite (btw, the *update layer statistics* is done on all the tables) while you started the thread about geopackage

**Comment by tghoward** [comment]
Another place it is possible to get off track with spatialite GUI is if you
don't know the projection code (SRID/EPSG). I wonder it this is why you
ended up with a longitude of 182.  The SRID needs to be specified for each
shapefile you import (when you import it). A good reference is here:

http://spatialreference.org/

Hope that helps.
Tim

**Comment by surf9** [comment]
Thanks everyone for your responses. I managed to get it working by updating layer statistics on all tables.
