### ISSUE TITLE
Dealing with Images

### ISSUE THREAD

**Issue by PipeManMusic** [geopaparazzi/geopaparazzi#251]
The image associated with notes inside geopaparazzi don't show up in the phones gallery. This means that as I'm collecting data, I have to take two pictures, one inside the app, then another with the standard camera app, of the same thing. Either having the photos also show in the standard gallery or allowing the images to be exported would solve this issue for me.

**Comment by moovida** [comment]
It is now possible to export the images from the export menu.

**Comment by PipeManMusic** [comment]
Wow! Thank you so much!!!!
