### ISSUE TITLE
Spatialite performance when need to render lots of polygons

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#264]
Hi there

I performed a small test weeks ago to load a spatialite db file containing lots of polygons. I found geopaparazzi was slow to render them especially where the extent was large in low resolution.

Is there anything that can be done to improve the performance?

**Comment by mj10777** [comment]
When a MapView is rendered, the extent being shown is known.

When retrieving geometries, this extent is being used with `ST_Intersects`, which will return this portions of the geometries being shown.

This the external class that `paint` the geometry in the MapView - will only receive that portion that can be seen on the screen.

However: to extract the geometry portions to be viewed, the whole table must be queried - which can be extensive.

The Spatial-Index is being used, which speeds up the query considerably, but other than that - nothing else can be done. 

The whole table **must** be queried to determine what is inside the portion of the MapView that is being shown.

Also during the startup of the Application, the extents of each table are being read and stored.

So while `painting`the active geometries, a check is done if the extent of the MapView is inside the extent of the table.

Only then (when inside) will the table be queried.
* i.e. when outside: the table will be ignored

These conditions cover, to my knowledge, everything one can do to render the geometries a speedily as possible.

**Comment by surf9** [comment]
Thanks for your input Mark.
