### ISSUE TITLE
Colouring polygons when using a spatialite db file

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#265]
Hi there

I'm wondering what is the best way to have different colours for different polygon data sets that are stored in the same spatialite db file? I think at present you can edit a spatialite table and edit that layer to have a different colour. What if all the layers are stored in the same table and need a different colour per polygon sets?

**Comment by mj10777** [comment]
Then you have a problem, which could possible be resolved with a generator
* that would start with the set colour
  * and then for each geometry add to the RGB value

But I have no idea where or how this would be implemented

**Comment by surf9** [comment]
Thanks for your input.
