### ISSUE TITLE
Check spatial index

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#266]
Still have to check this, but working on other stuff I think we are doing the bbox query wrong to get spatialite data, making things slower. It might be better to make a SpatialIndex query and afterwards check intersection on the geometries.
But this still has to be checked.

**Comment by mj10777** [comment]
Here great care must be taken to insure that it is done correctly.

I looked into this, quite thoroughly, during the reorganization
* the cause being, while using the berlin-street intersections, there a a noticeable pause while rendering

I read though the spatialite forum and worked out, what I though, was a better solution
* that also seemed to be swifter while rendering

Thankfully I asked about this and Sandro gave good arguments for **not** doing it in this way

https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!searchin/spatialite-users/ST_Intersects/spatialite-users/0FXMx2xgHPk/SZD3B7WkWO0J

My final conclusion was to leave as it was, based on Sandros opinion that this was the best way to return the correct results.

**Comment by moovida** [comment]
Thanks, that is good to know.
