### ISSUE TITLE
Spatialite 4.3.0 and source code changed needed for RasterLite2

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#267]
I have adapted the `libjsqlite-spatialite-android` project to use the present developer version of both
* spatialite
* rasterlite2

The `spatialite_rasterlite2 was deleted` and a new one rebuilt from master as of today.
* the libs were replaced
* in `SPL_Rasterlite.java` 
   * needed code changes were made, due sql-functions that were renamed in the RasterLite2 project
      * `GetMapImage` to `GetMapImageFromRaster` 
         * nothing more needs to be done

`getRasterTileInBounds` 
* which is called from outside `SPL_Rasterlite.java`
   * was *not* renamed

The compiled libraries can be downloaded with
```bash
wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20150607.libjsqlite.4.3.0.tar.bz2
wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20150607.libjsqlite.R4.3.0.tar.bz2
```

---
Sandros last assumption was that RasterLite2 is 4/5 complete.

So when Spatialite 4.3.0 is final
* a `geopaparazzi_rl2` version would then be realistic

**Comment by mj10777** [comment]
I have cleaned up the main wiki page for the driver:

https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki

**Comment by moovida** [comment]
Good, I will give this a try asap and integrate

**Comment by mj10777** [comment]
I have updated the librarys to 4.3.0-rc0

The archive can be downloaded at:
https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Configuration-used-presently

the branch spatialite_rasterlite2 has also been updated.

Also the needed changes in SPL_Rasterlite.java have been committed.

**Comment by moovida** [comment]
You pushed your stuff to master. Has that been an error? This is not the usual way to go. 
I will start looking into what you pushed.

**Comment by moovida** [comment]
merged in. Will solve issues, if there are, when we see them. Looks good to me up to now.
