### ISSUE TITLE
Datasource list - extra sort

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#268]
It might be a good idea to add an extra sort for raster source that have more than one entry
* as will often happen with RasterLite2 Databases

![20150608 datasource sort](https://cloud.githubusercontent.com/assets/4899405/8035279/5b04117e-0def-11e5-8d6e-81f09de46dce.png)

**Comment by mj10777** [comment]
I assume that the sorting is being done in
* `MapsDirManager.java`.createTree()

and the value needed is in
* `spatialTable.getTitle()`

but I am afraid, that it has been to long for me to understand how the sorting after that is being done.

**Comment by moovida** [comment]
I will have to look into this. To do so I assume I will have to add the rasterlite support.
I think that could be done from now on.
Will I just need to merge in the rasterlite branch, right?
Also, I would need a sample database, since I will not create rasterlite db soon.
I will try to work on this by the end of the week.

**Comment by mj10777** [comment]
The only code changes needed is in
* SPL_Rasterlite.java
   * change 'GetMapImage' to 'GetMapImageFromRaster'

**Comment by mj10777** [comment]
In the present RasterLite2, Sandro has foreseen the need to create an Image from Vector-Data
* thus the rename of everything with an extra 'FromRaster'
   * there is also a corresponding 'FromVector' function for everything
      * but is not documented yet, but may be useful for the future

**Comment by moovida** [comment]
Would that also imply sld support? That would be an incredible feature to style vector data in a complex way and paint them as tiles?

**Comment by mj10777** [comment]
I will prepare a small database with about 5 maps and place it on my servers and sent you the `wget` command to download it.

**Comment by mj10777** [comment]
Possibly, but not yet documented - so I do not understand how it all works
* but my impression is that he has concentrated on combining everything with styling  
* and possibly combing the different Raster/Vector together and return the result as an image

He has promised an extensive documentation, so until then ...

**Comment by mj10777** [comment]
I really don't know what `sld` means.
Have a look at:
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=4.3.0+functions

`4 - SE Styling helper` 
* is that `sld`?

**Comment by mj10777** [comment]
BTW. you are up early ...

**Comment by mj10777** [comment]
Here is a database with 5 maps. (118.4 MB)

```bash
wget http://www.mj10777.de/public/download/rasterlite2/1867.berlin_data.db
```
the final result should be listed as:
```
1786 Grundriss von Berlin - 1:12000
1809 Grundriss von Berlin mit Stadtbezirke - 1:5800
1811 Grundriss von Berlin mit Stadtbezirke - 1:5800
1846 Grundriss von Berlin - 1:5800
1867 Berlin Liebenow - 1:6250
```

**Comment by moovida** [comment]
Thanks for the db.

SLD is the http://en.wikipedia.org/wiki/Styled_Layer_Descriptor , which some open GIS completely support. That would mean that some advanced styling would be supported in geopap without implementing it.

PS: you also are up quite early :-)

**Comment by mj10777** [comment]
Symbology Encoding (SE)
* well, that looks like Sando is working with

**Comment by mj10777** [comment]
If you open that database with the present spatialite-gui
* you will see a Folder called `Styling (SLD/SE)`
![20150609 sld_se](https://cloud.githubusercontent.com/assets/4899405/8051493/38691888-0e7d-11e5-8627-9afb20d5acb1.png)

So that is where everything will be stored
* How all this works and how it will be filled, the future documentation will show

**Comment by moovida** [comment]
I merged in your rasterlite2 branch, but on your berling database in the checkDatabaseTypeAndValidity method, 
DatabaseCreationAndProperties.JavaSqliteDescription.equals("")
fails, because it is:
sqlite[3.8.10.2],spatialite[4.3.0-RC0],proj4[Rel. 4.9.1, 04 March 2015],geos[3.4.2-CAPI-1.8.2 r3921],spatialite_properties[HasIconv[1],HasMathSql[1],HasGeoCallbacks[0],HasProj[1],HasGeos[1],HasGeosAdvanced[1],HasGeosTrunk[0],HasLwGeom[0],HasLibXML2[1],HasEpsg[1],HasFreeXL[0],HasGeoPackage[1],target_cpu[armeabi-v7a]],rasterlite2_properties[1.6.10]]

so the driver is not recognised as rasterlite2.

Maybe I am doing something wrong, since you are working with this since some time now?

**Comment by moovida** [comment]
Sorry, forget the above. I might have done something wrong. Now it is working. I'm on it.

**Comment by moovida** [comment]
Btw, nice nice ancient Berlin maps!
I wonder what the "Lustgarten" behind the "Koenigl. Schloss" might have been of use for :-D

Everything seems to work with your maps. 
I hope I will soon be able to produce some maps also to do some more checks. 

The binaries are 4MB more than before but I guess that is ok for the upcoming rasterlite feature.

**Comment by mj10777** [comment]
2015-06-19 8:29 GMT+02:00 Andrea Antonello <notifications@github.com>:

> Btw, nice nice ancient Berlin maps!
> I wonder what the "Lustgarten" behind the "Koenigl. Schloss" might have
> been of use for :-D
>
Well, in much older days, there was the Palace-Garden, created as was done
in Versaille.
- Berliners tend to be practical about the name given
-- thus 'Lust'
--- and if the church does not like the name, even better

**Comment by mj10777** [comment]
2015-06-19 8:20 GMT+02:00 Andrea Antonello <notifications@github.com>:

> I merged in your rasterlite2 branch, but on your berling database in the
> checkDatabaseTypeAndValidity method,
> DatabaseCreationAndProperties.JavaSqliteDescription.equals("")
> fails, because it is:
> sqlite[3.8.10.2],spatialite[4.3.0-RC0],proj4[Rel. 4.9.1, 04 March
> 2015],geos[3.4.2-CAPI-1.8.2
> r3921],spatialite_properties[HasIconv[1],HasMathSql[1],HasGeoCallbacks[0],HasProj[1],HasGeos[1],HasGeosAdvanced[1],HasGeosTrunk[0],HasLwGeom[0],HasLibXML2[1],HasEpsg[1],HasFreeXL[0],HasGeoPackage[1],target_cpu[armeabi-v7a]],rasterlite2_properties[1.6.10]]
>
'rasterlite2_properties[1.6.10]' : for some reason the real value is not
used
- all of these projects use 'VERSION'. For some reason this get the the
version number of the last project.
-- this will, however, be empty if not compiled with rasterlite2.

**Comment by moovida** [comment]
this is done

**Comment by mj10777** [comment]
This is still not being sorted properly:

![20150620 datasource sort](https://cloud.githubusercontent.com/assets/4899405/8266783/df5bddb6-1741-11e5-8ee8-913d6e8bf324.png)

**Comment by moovida** [comment]
I can't see the main folder name.
I used your db and it looks good.
![photo_2015-06-20_14-36-52](https://cloud.githubusercontent.com/assets/390250/8267273/e587fbb2-1759-11e5-8d39-9132bb033ca4.jpg)

**Comment by mj10777** [comment]
Well 1786 comes before 1867 as does 1811, 1846 and 1809.

**Comment by moovida** [comment]
Ahhh, right. Didn't notice that. Let me check.

**Comment by moovida** [comment]
ok, done, coming with next push

**Comment by mj10777** [comment]
Allen arrived this morning and is coming over at 4.
* I would like to give him the latest version 
   * will the puch be done by then?

**Comment by moovida** [comment]
Yes, definitely. I have to remove some unused code and will then push. 
I will then head out in the mountain to do some testing as well. In the next days I will be on geopap, so if something pops up, just shout.

**Comment by moovida** [comment]
I noticed that through this, also all MBTiles sources are now visualized as folder with subdatasets. 
Since MBTiles can have more tables, I assume that makes perfectly sense and maybe before was missing the feature. Am I right?

**Comment by mj10777** [comment]
No, Mbtiles can have only one Raster in a file.
GeoPackages can have more than one

The sorting is now correct.

**Comment by moovida** [comment]
Outch, then mbtiles needs to be corrected. They now appear like the rasterlite with subfolder.

**Comment by moovida** [comment]
ok, fixed

**Comment by mj10777** [comment]
This is now a very clean solution, which takes care of all situations
