### ISSUE TITLE
show center coords when panning

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#270]
would be fun to have

**Comment by mj10777** [comment]
Very nice
* and now all that is needed is an option to show it in the srid of the active map

**Comment by moovida** [comment]
Not sure what you mean here.
What is the *active* map? Or are you saying that rasterlite can be in any projection and it is reprojected on the fly when serving tiles?

**Comment by mj10777** [comment]
Am 21.06.2015 11:41 schrieb "Andrea Antonello" <notifications@github.com>:
>
> Not sure what you mean here.
> What is the active map? Or are you saying that rasterlite can be in any
projection and it is reprojected on the fly when serving tiles?
yes.

**Comment by mj10777** [comment]
Sorry, I answered that in the wrong place.

Each map retains its own original srid projection.
* so each request for an area, a BBOX must (in the end) be in that srid

So, just as with the geometries, a ST_Transform() will be done, where not Wsg84(), for the BBOX
* rl2_GetMapImageFromRaster

This has the advantage, that maps being stored must **not** be warped into wsg84
* as must be done for mbtiles

In your case, I assume, most of your topographic maps that you may use
* will be in a meter Italian system
   * this system will be retained in the Database

It can be assumed, that the user often `knows` their own system better than in wsg84
* in Berlin, when moved, only that last 3/4 digits change
   * and that value is is degrees - which is not very helpful

In a meter system, you would have a better idea
* in how far you are moving
   * and this be a cheap distance calculator
      * `how far away am I to the point I am walking to?`

---

Yesterday, together with Allen and a Canadian friend
* who also brought a visitor from Canada
   * that friend became very interested in geopaparazzi 
      * when shown on the map the placed he wanted to go
      * saw the track of the route we had been going through
      * **and** find his way back if he go thoroughly lost
         * which seems to have happen in the last day while wandering around by himself

He was, BTW, a great note taker
* I may show him that functionality as well, when we next meet

**Comment by moovida** [comment]
Nice, I like that one. Being able to have data in their own projection. And I agree about the fact that degrees are never of use as measurement :-) 
I has added a method **longLat2Srid** to the **AbstractSpatialTable** which for now is implemented as placeholder:

```java
    @Override
    public double[] longLat2Srid(double lon, double lat) {
        throw new RuntimeException("Not implemented yet");
    }
```

inside the implementing Spatial tables:
* CustomTileTable.java
* MapTable.java
* SpatialRasterTable.java
* SpatialVectorTable.java

Can you supply an implementation for those with the proper queries?

**Comment by mj10777** [comment]
Yes. I was having thoughts about this yesterday.

Pre-Conditions would/could be:
* at least 1 connection to any spatialite database
   * this could be stored as a copy in somewhere general
      * `SpatialiteDatabaseHandler` could set this when `NULL`

After read all Database and if **no** Databases found
* a **memory* Database could be created
   * and a `SELECT InitSpatialMetadata(1);` executed
      * creates `spatial_ref_sys` needed for transormations

That connection could then be used to execute any general spatial queries
* in this case `ST_Transform(..)`

**Comment by moovida** [comment]
Actually, since the moment mapsforge data extraction has been enabled, it is assured that there is at least one spatialite connection: to the database **mapsforge_extracted.sqlite** which supplies the tables: 
* osm_roads
* osm_contours
* osm_waterlines

**Comment by mj10777** [comment]
Could this connection then be stored somewhere where `longLat2Srid` could access it?

**Comment by moovida** [comment]
Wait, now that I think about it. I though that the SpatialTables would have access to the db. Instead I see that only the Handler has. 
I will have to think about it a bit.

**Comment by mj10777** [comment]
Can a copy of the first Database be used to set Database dbJava in AbstractSpatialTable and use that?

**Comment by moovida** [comment]
Closing this issue, this conversation has been done in some pull request already.
