### ISSUE TITLE
RasterLite2 issues

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/geopaparazzi#271]
When browsing around the berlin map, at some point I get a big bunch of:

06-20 08:24:09.391  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: Could not find image: RASTERLITE2: Attempt to get length of null array
06-20 08:24:09.391  19784-20010/eu.hydrologis.geopaparazzi I/GPLOG_ERROR﹕ Could not find image: RASTERLITE2: Attempt to get length of null array
06-20 08:24:09.417  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: java.lang.NullPointerException: Attempt to get length of null array
            at eu.geopaparazzi.mapsforge.mapsdirmanager.maps.tiles.GeopackageTileDownloader.executeJob(GeopackageTileDownloader.java:123)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:82)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
06-20 08:24:09.417  19784-20010/eu.hydrologis.geopaparazzi I/GPLOG_ERROR﹕ java.lang.NullPointerException: Attempt to get length of null array
            at eu.geopaparazzi.mapsforge.mapsdirmanager.maps.tiles.GeopackageTileDownloader.executeJob(GeopackageTileDownloader.java:123)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:82)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
06-20 08:24:09.557  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: Could not find image: RASTERLITE2: Attempt to get length of null array
06-20 08:24:09.557  19784-20010/eu.hydrologis.geopaparazzi I/GPLOG_ERROR﹕ Could not find image: RASTERLITE2: Attempt to get length of null array
06-20 08:24:09.590  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: java.lang.NullPointerException: Attempt to get length of null array
            at eu.geopaparazzi.mapsforge.mapsdirmanager.maps.tiles.GeopackageTileDownloader.executeJob(GeopackageTileDownloader.java:123)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:82)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
06-20 08:24:09.590  19784-20010/eu.hydrologis.geopaparazzi I/GPLOG_ERROR﹕ java.lang.NullPointerException: Attempt to get length of null array
            at eu.geopaparazzi.mapsforge.mapsdirmanager.maps.tiles.GeopackageTileDownloader.executeJob(GeopackageTileDownloader.java:123)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:82)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
06-20 08:24:09.723  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: Could not find image: RASTERLITE2: Attempt to get length of null array
06-20 08:24:09.723  19784-20010/eu.hydrologis.geopaparazzi I/GPLOG_ERROR﹕ Could not find image: RASTERLITE2: Attempt to get length of null array
06-20 08:24:09.753  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: java.lang.NullPointerException: Attempt to get length of null array
            at eu.geopaparazzi.mapsforge.mapsdirmanager.maps.tiles.GeopackageTileDownloader.executeJob(GeopackageTileDownloader.java:123)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:82)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
06-20 08:24:09.753  19784-20010/eu.hydrologis.geopaparazzi I/GPLOG_ERROR﹕ java.lang.NullPointerException: Attempt to get length of null array
            at eu.geopaparazzi.mapsforge.mapsdirmanager.maps.tiles.GeopackageTileDownloader.executeJob(GeopackageTileDownloader.java:123)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:82)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
06-20 08:24:09.877  19784-20010/eu.hydrologis.geopaparazzi I/GEOPAPARAZZI﹕ 2015-06-20 08:24:09: UU;ERROR_GEOPAPARAZZI;GEOPACKAGETILEDOWNLOADER: Could not find image: RASTERLITE2: Attempt to get length of null array

Not sure if it is related, but it also crashed during panning.

**Comment by mj10777** [comment]
1) As long as I have been using it, it has never crashed while panning.
2) Why is this coming from `GeopackageTileDownloader` ?

**Comment by moovida** [comment]
Ah, good, this should not come from there, right? I am on other stuff right now and could not pursue that. I was wondring if the GeopackageTileDownloader  would take care of RasterLite also. If you say it doesn't, I will check why it is even instantiated.

**Comment by mj10777** [comment]
I am just looking.
* it checks for RasterLite2
   * so I think the class name is just incorrect or misleading

Looking for the point where it crashes now

**Comment by mj10777** [comment]
seems to happen at this code:

```
            try {
                decodedBitmap = BitmapFactory.decodeByteArray(rasterBytes, 0, rasterBytes.length);
            } catch (Exception e) {
                // ignore and set the image as empty
                GPLog.error(this, "Could not find image: " + tileQuery, e); //$NON-NLS-1$
            }
```

* so `rasterBytes` may be null
   * `SPL_Rasterlite.getRasterTileInBounds` return NULL if nothing is found

So it would be interesting to know
* which map
* which Zoom-level
* which position

With that we would learn if this is just out of range
* and a blank image should be returned
   * by `SPL_Rasterlite.getRasterTileInBounds` if NULL

**Comment by moovida** [comment]
Ok, I will check this in a little while and report zoom-tilexy, maybe you can tell if there is a missing piece.
If that is the case I will insert the empty image. We should have that one already ready somewhere in the code, since it is used by other classes. I will make that one available.

**Comment by mj10777** [comment]
the best thing to do is to check in

rl2_GetMapImageFromRaster(..)
* is to dump out the result of s_sql_command
   * if `return ba_image;` would return NULL

With that sql I could check here what rasterlite2 returns

**Comment by mj10777** [comment]
* `RL2_GetMapImageFromRaster` will return `NULL on invalid arguments or if any error occurred.` 
  * according to the old documentation

If there was memory or other internal error 
* an exception error of `SPL_Rasterlite` would have been printed

I just tried down to zoom 22 and moving out of range
* no error occurred that I could see in the Log-book
   * but there are tons of gps messages being written every second, so I may have missed it

**Comment by moovida** [comment]
> but there are tons of gps messages being written every second, so I may have missed it

Do you have all 3 loglevels switched on? The last one should usually be left of, since it enables all gps logs, which make everything else unreadable. If you uncheck the last *logABS*, it should be better for you.

**Comment by mj10777** [comment]
I just tried retrieving a berlin tile on a paris map in spatialite_gui

``SELECT RL2_GetMapImageFromRaster('paris_olan_de_ville.1790',ST_Transform(BuildMBR(13.377227783,52.516220864,13.378601074,52.517056554,4326),3068),256,256,'default','image/png','#000000',0,80, 1)
``` 

and it returns NULL.

* so `NULL`
   * can also be considered **no result**

`rasterBytes` should be checked in `GeopackageTileDownloader.executeJob`:
* and then return the blank image
   * which occurs when `decodedBitmap == null`

```
            Bitmap decodedBitmap = null;
            if (rasterBytes != null) {
            try {
                decodedBitmap = BitmapFactory.decodeByteArray(rasterBytes, 0, rasterBytes.length);
            } catch (Exception e) {
                // ignore and set the image as empty
                GPLog.error(this, "Could not find image: " + tileQuery, e); //$NON-NLS-1$
            }
            // check if the input stream could be decoded into a bitmap
            if (decodedBitmap != null) {
                // copy all pixels from the decoded bitmap to the color array
                decodedBitmap.getPixels(this.pixels, 0, tileSize, 0, 0, tileSize, tileSize);
                decodedBitmap.recycle();
            } else {
                for (int i = 0; i < pixels.length; i++) {
                    pixels[i] = Color.WHITE;
                }
            }
           }
```

I will look at the set log levels and check again.

**Comment by mj10777** [comment]
OK, that was it (logABS)
* I can now see these errors

The above extra:

if (rasterBytes != null) 
{
}

should resolve this.

**Comment by moovida** [comment]
Great, thanks, I will place this in in a few minutes and let you know.

**Comment by mj10777** [comment]
Do you think there may be problems for a lot users with small amounts of memory on there telefon
* to be able to use the RasterLite2 version ?

**Comment by moovida** [comment]
You mean because of the additional 3Mbytes? Or because if the imagery part?

In my understanding both should not be a big issue (i.e. not bigger than geopaparazzi already is). I assume the tile generator for rasterlite behaves exactly like the other tile sources in terms of occupying and releasing memory, right?

**Comment by moovida** [comment]
Just to make sure. In you above code snippet the 

if (rasterBytes != null) 
{

part should close right before the line:
// check if the input stream could be decoded into a bitmap

so that it stays NULL and the white image is generated. Could it be that in your example the closing bracket is to far down?

**Comment by mj10777** [comment]
Oh yes, it is very memory friendly library
* and wen the `RL2_PyramidizeMonolithic(..)` is used when creating the database
   * scaled images/tiles will be created (which make the Database bigger)
      * and are used when retrieving a portion, thus less work for the machine to resize

**Comment by mj10777** [comment]
It should be closed before this

```
// check if the input stream could be decoded into a bitmap
            if (decodedBitmap != null) {
```

so that the blank image can be created

**Comment by mj10777** [comment]
Yes, after re-reading your message

**Comment by moovida** [comment]
Ok, everything is in place now. And it works, will close this.


Regarding the memory thing, I am very happy about that. I will need to gain more insight about the necessary functions to create RasterLite2 datasets from java, since I want that to be supported in the JGrasstools based applications. Right now I am working (as you saw in the spatialite list) on the vector import part.

**Comment by mj10777** [comment]
the best ways is to do this with a sql script
* pre-condition it that the environment variable
`SPATIALITE_SECURITY=relaxed` 
* is set to allow the importing of external files
