### ISSUE TITLE
SpatialiteUtilities.collectBoundsAndCenter use of srid -1 causes error

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#273]
Raster2 Images that have an srid of '-1'
* these are non-georeferenced images

there are, of course, normal `geometries` that can have a srid <=0
* with this change, they too will not be loaded
   * and therefore cause no problems

cause collectBoundsAndCenter to throw an error
* since they cannot be transformed to Wsg84

```
06-20 11:25:32.937 20378 20422 I GEOPAPARAZZI: 2015-06-20 11:25:32: UU;ERROR_GEOPAPARAZZI;SpatialiteUtilities: .collectBoundsAndCenter Bounds[SELECT ST_AsBinary(CastToXY(ST_Transform(MakePoint((0.0 + (9975.0 - 0.0)/2), (0.0 + (1004.0 - 0.0)/2), -1),4326))) AS Center,ST_AsBinary(CastToXY(ST_Transform(BuildMBR(0.0,0.0, 9975.0,1004.0, -1),4326))) AS Envelope ]: null
```

So until normal images can be supported with mapsforge
* these Rasters must be avoided

class SpatialiteDatabaseHandler.collectVectorTables()
* at line 772
   *  ' if (sa_string.length == 4) {' 

```
                    // must be > 0 for Wsg84 support  (no Tranformation possible)
                    int i_srid = Integer.parseInt(s_srid);
                    if ((sa_string.length == 4) && (i_srid > 0)) {
```

* just compiled, and tested

**Comment by mj10777** [comment]
This seems now to work correctly
* found no other messages in the log which found cause for worry

**Comment by moovida** [comment]
done - to be tested, I have no such image

**Comment by mj10777** [comment]
Once the next push is done, I will test this again
* after my changes it worked

**Comment by moovida** [comment]
Ok, push is done.

**Comment by mj10777** [comment]
After the last changes
* the geometries and RasterLite2 Rasters
   * with an srid <=0 are **properly** ignored
