### ISSUE TITLE
Deselecting Images in MapView not effected

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#280]
(From Allen)
When selecting the taken Images in the MapView
* Dialog shows Images as deselected
   * but when returning to the Map, the Image-Icons can still be seen
      * returning back to the dialog, everything is selected

All Notes
* invert selection
   * return to Map

**Comment by moovida** [comment]
The selection in the notes list (I assume you mean that one) is not to toggle visibility. It is used only to delete several notes at once. I am explaining techniques right now in the new manual.

Images and notes can be deselected in the gps data list view.
Images right there and notes inside the note properties view.
