### ISSUE TITLE
AbstractSpatialTable - Refactoring needed

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#281]
While attempting to adapt the needed logic to support RasterLite2-Styles support for
* Raster and Vector-Styles

I see the need to refactor the code the process between
* the collection of the Database Information in 
   * `GeneralQueriesPreparer` and `DatabaseCreationAndProperties.checkDatabaseTypeAndValidity`
* creation of the classes based on `AbstractSpatialTable`

```java
     * Return layerTypeDescription
     * <p/>
     * <p>[SpatialRasterTable] 'SpatialTable'
     * <p>[SpatialVectorTable] 'SpatialView'
     * <p>[SpatialRasterTable] 'MBTiles'    
     * <p>[MapTable] (Mapsforge) 'Map'   
     * <p>[CustomTileTable] 'Mapurl'       
     * TODO: ? add to 'TableTypes':
     * - added as GPKGRASTER/GPKGVECTOR
     * <p>[SpatialRasterTable] 'GeoPackage_tiles'
     * <p>[SpatialVectorTable] 'GeoPackage_features'
```

these are created in:
* `SpatialiteDatabaseHandler`
   * `collectGpkgTables()`
   * `collectVectorTables()`
* `MbtilesDatabaseHandler`
   * `getSpatialRasterTables()`
* `CustomTileDatabaseHandler`
   * `getTables()`
* `MapDatabaseHandler`
   * `getTables()`

5 functions that need to be adapted when adding anything new
* as at the moment for Vector-Style, Raster-Style for RasterLite2
   * changes need to made **everywhere** where `AbstractSpatialTable` is used

---

**Goals**:
* simplify the constructor of `AbstractSpatialTable` (and the derived classes)
   * String databasePath
   * String mapType
   * String vector_key
      * which would contain the `layerTypeDescription`
         * values from `SpatialDataType` and `TableTypes`
            * for `TableTypes`: **GPKGRASTER** and **GPKGVECTOR** have been added
   * String vector_value
      * `vector_value`
         * can be **extended** at need without changing all the constructors and validity checking
            * which I had to do when adding the RL2-Raster-Style logic
* simplify the creation of classes `AbstractSpatialTable`
   * `DatabaseHandler` functions doing this will probably not have to be adapted
      * when new features are added to, as now needed for RasterLite2
         * and there will be more coming
* the parsing of `vector_key,vector_value`
   * should be done in 1 place (instead of now in 4 or 5 places)

---

The process would then be:
* inside the constructor of `AbstractSpatialTable`
   * ` int i_rc=parse_vector_key_value(vector_key,vector_value);`
      * here **everything** needed will be done
         * set the needed values
         * determine if the Table is considered valid
            * `SpatialVectorTable` without a `SpatialIndex` 
               * would be **invalid**

Inside the `DatabaseHandler`
* `vector_key`
   * must (in most cases) still be split to retrieve the `layerTypeDescription`
      * to decide on what type of class should be created
         * `SpatialRasterTable` or `SpatialVectorTable` 

```java
SpatialVectorTable table = new SpatialVectorTable(getDatabasePath(),vector_key,vector_value)
if (table.IsValid())
 vectorTableList.add(table);
```

---

Not all classes use `GeneralQueriesPreparer` to create
* `vector_key,vector_value`
   * `MapTable`, `CustomTileTable` and the special case for `MBTiles` 
      * where they would have to created manualy

```java
String layerType = SpatialDataType.MBTILES.getTypeName();
String vector_key=databaseFileNameNoExtension+";0:"+layerType+";"+databaseFileNameNoExtension+";"+tableName+";default";
String s_bounds=this.boundsWest + "," + this.boundsSouth + "," + this.boundsEast + "," + this.boundsNorth+ "," + this.centerX+ "," + this.centerY;
String vector_value=this.minZoom+";"+this.maxZoom+";4326;"+defaultZoom+";0;"+s_bounds+";?,?,?";
SpatialRasterTable table = new SpatialRasterTable(databasePath, vector_key,vector_value)
if (table.IsValid())
 rasterTableList.add(table);
```

---
One major problem with the `DatabaseHandler` was
* after the class creation
   * extra tasks needed to be done **afterwords**
      * `SpatialiteDatabaseHandler.collectVectorTables()` for `SpatialVectorTable`

In all cases, the bounds - if not in **WSG84** must be transformed
* for which a `global` Spatialite-Database connection could be used
   * more to that later

However for `SpatialVectorTable`
* the Spatialite-Database connection for that table is needed
   * `DaoSpatialite.collectTableFields(dbJava, table_name);`

Since, at the moment, `AbstractSpatialTable` 
* does **not** have a copy of the `DatabaseHandler` Spatialite-Database connection
   * `parse_vector_key_value` **cannot** complete this task

Since a **major** Goal is to simplify the maintenance in **one** place
* I would like to avoid the present solution where
   * the `DatabaseHandler` is doing extra tasks **after**  the class has been created

So a policy decision is needed here
* either
   * store a copy of the Spatialite-Database connection in  `AbstractSpatialTable` 
      * where it must **never** be closed
* or
   * pass the Spatialite-Database connection to `AbstractSpatialTable` in the constructor
      * using it as needed **only** during the construction process
         * without saving it

I would prefer the **first**  option
* then `longLat2Srid(..)` (at present in `SpatialRasterTable`) 
   * when moved to `AbstractSpatialTable`
      * could also be done for **all** classes using `AbstractSpatialTable`

---
At present I built in logic to store the **first** found Spatialite-Database in
* `SpatialiteUtilities` with a get/setDatabase()
   * being set in `checkDatabaseTypeAndValidity`

Missing is still the logic
* when not set when `getDatabase()` is called
   * a Memory Database is created

The intention was for this to be used for
* `longLat2Srid(..)`
* transforming bounds to **WSG84** inside `parse_vector_key_value`

but because of the above problem (**collectTableFields**)
* this is **not** enough

So a policy decision is needed here
* if `AbstractSpatialTable` may share the `DatabaseHandler` Spatialite-Database connection
   * either storing **or** only passing the connection (without storing) to the constructor

---

The result of this will be submitted to the
* `rasterlite2_styles` branch

The **first** commit to this branch is based on the present code
* where everything had been manually adapted
   * it will display a RasterLite2 Database with a Raster-Style

The (indended) **second** commit to this branch 
* will be based on the above changes
   * that compiles and (hopefully) runs as the first

Timeframe:
* as fast as possible
   * so that `geopaparazzi` can be adapted to support everything practical
      * that Sandro has build into RasterLite2

**Comment by mj10777** [comment]
The major coded change have now been made.
* the Spatialite-Database connection has been added to `AbstractSpatialTable`
* in `SpatialiteDatabaseHandler`
   * `collectGpkgTables()` and `collectVectorTables()` have benn replaced with a 
      * `collectTables()`

Work still needed to be done to insure that 
* `AbstractSpatialTable.parse_vector_key_value()` is complete

The usage of `vector_key` and  `vector_value`
* have been documented where used

The changes have been committed to `rasterlite2_styles` branch

**Comment by mj10777** [comment]
The `rasterlite2_styles` branch
* is now nearing a point that it can be merged
   * testing directly from the branch can now be done

---
`AbstractSpatialTable`
* now stores the pointer to the `SpatialiteDatabaseHandler` Database connection
* for `MBTiles`, `Map` and `Mapurl` 
   * this can be `NULL`
   * the file name being used 
      * is give as an extra field in `vector_value`
* `isValid()`
   * is called in `SpatialiteDatabaseHandler`
      * and only == `true` will the Table be added

`SpatialRasterTable`
* `longLat2Srid()`
   * has be implemented
      * calling `DaoSpatialite.longLat2Srid(getDatabase(1),lon,lat,getSrid());`

`SpatialiteDatabaseHandler`
* `collectGpkgTables()` and `collectVectorTables()`
   * have been **replaced** with `collectTables()`

`SpatialiteUtilities`
* support for a Memory-Spatialite-Db **upon demand**
   * `Database getMemoryDatabase()`
      * **Note** [20150722]: this has not yet been tested
      * `DaoSpatialite.longLat2Srid(getDatabase(1),lon,lat,getSrid());`
         * would use this in cases when:
            * the Database connection [`MBTiles`, `Map` and `Mapurl`]
               * **and** the srid != `Wsg84` 
                  * only then for [`Mapurl`]

`TableTypes` 
* the following have been added:
   * `"RL2_Vector`
   * `"RL2_Raster`
   * `GeoPackage_features`
   * `GeoPackage_features`

`SPL_Geopackage`
* support for Recovery mode has been implemented
   * mainly when the 
      * `min_x,min_y,max_x,max_y` of `gpkg_contents` are **not** set
         * which, it seems, all software ignore (including Spatialite)


---
**General changes**
* Where still hard-coded (and found)
   * The enum functions are used, mainly
      *  `SpatialDataType.RASTERLITE2.getTypeName()`
      * `TableTypes.RL2RASTER.getDescription()`

**Comment by mj10777** [comment]
A sample showing
* on the right
   * your beloved trees (with your styling)
* a Photo stored in Rasterlite2
   * with geometries in the foreground
      * since the photos *float'  over Berlin

![20150722 rl2_styles](https://cloud.githubusercontent.com/assets/4899405/8830606/6423215c-309d-11e5-9185-a62ad9bdb89f.png)

**Comment by moovida** [comment]
Great great stuff @mj10777 . My return from the Foss4g Europe has been quite cray and I have piles of work to finish. As soon as I have time, I will go through all your comments (only could quickly read through them) and give feedback. Thanks

**Comment by mj10777** [comment]
In the mean time, further code refactoring has been attempted
* Goal: creating an Application independent
   * `geopaparazzispatialitelibrary` and
   * `geopaparazzimapsforge`
      * with a (mapsforge specific) Overlay (called GpsGeometryOverlay)
Both of these should be completely independent of of the other libraries

Whereby:
* `geopaparazzimapsforge`
   * is dependent on `geopaparazzispatialitelibrary`

---
Based on the following criteria:
* code portions (i.e. classes) found in 
   * `geopaparazzispatialitelibrary` AND
   * `geopaparazzimapsforge`
using classes in `geopaparazzilibrary`

But also:
* displayed in a gui-based MapView
   * gps, gpx
* general, reusable, gui-components 
   * dialogs such as `DirectoryBrowserActivity`

where one can assume other Applications would find useful
* without having to **reinvent the wheel**

---
For this, a **library** directory has been added.
* `eu.geopaparazzi.spatialite` 
   * `database`
      * `spatial`
         * containing everything that has been used up to now
   * `library`
         * containing copied or moved from `geopaparazzilibrary`
            * using the same directory, file-names

---
The committed changes in branch `rasterlite2_styles`
* now use this structure

All references inside `geopaparazzi.app` and `geopaparazzimapsforge`
* now point to `eu.geopaparazzi.spatialite.library`

For those Classes **not** used inside `geopaparazzilibrary`
* the Classes have been **removed** from `geopaparazzilibrary`

For those Classes  used inside `geopaparazzilibrary`
* the Classes remain as copies

* In `eu.geopaparazzi.spatialite` 
   * the **dependency** to `geopaparazzilibrary`has been **removed**
      * *build.gradle*
```
dependencies {
     // compile project(":geopaparazzilibrary")
         compile files('libs/httpmime-4.2.2.jar')
         compile files('libs/android-support-v4.jar')
}
```

And all resulting resources copied into `eu.geopaparazzi.spatialite` 

---
The next stage, which I will try to complete today, will bee to **add** the **dependency**
* of `geopaparazzispatialitelibrary` to `geopaparazzilibrary` and
   * remove the Classes in `geopaparazzilibrary`
      * that are now a part of `geopaparazzispatialitelibrary`

**Comment by mj10777** [comment]
--part 2 --
While working on building in the dependency of
* `geopaparazzispatialitelibrary` into `geopaparazzilibrary`

this part will contain a list of directories, where the classes inside do **not** have further dependencies
* `geopaparazzilibrary.library`
   * **bluetooth**

**Comment by moovida** [comment]
Hi @mj10777 , I am quite worried about this proposal of yours. It is true that Geopaparazzi also wants to act as a library to create location based apps, but it is meant for survey-type apps that base on the geopaparazzi database model, not *any* gps or spatialite based app. 
That is the reason some stuff (that you decided to move/copy into spatialite library) has been put into the library project.

I have been able to only browser for about half an hour your changes, but I can state that this proposal will never make it into the master branch. First because it is not the way I designed Geopaprazzi to work. I don't see why gpx and network and other packages should be moved (or even worse duplicated) into the spatialite project. Even the LibraryConstants has been copied and now has a new epsg added, which is really really app specific:  SRID_BRANDENBURGER_TOR_187999

Some comments:
* the rasterlite2 style part should stay in a separate pull request. At some point I should be able to review it and merge it in. Time has not been my friend lately.
* the splitting of architecture should be done by first discussing thing and involving me (I might have had good reasons to do things the way they are). I don't think that for that emails would be enough. But for now I am afraid I don't see the possibility for this kind of split any time soon.

**Comment by mj10777** [comment]
After saving the above to a branch `spatialite_handler`
* `rasterlite2_styles` has been reverted back to it's original status
   * with the exception that 'GeopaparazziOverlay.drawOverlayBitmap`
      * splitted into functions for each type being drawn

---
Should I upload the `spatialite_handler` branch
(where the duplicated have been removed, that what I was working on today)
* so that at some time, it can be looked into again?

---
SRID_BRANDENBURGER_TOR_187999
* is needed inside the Rasterlite2 logic
   * Wsg84 area request **cannot** be transformed into pixels
      * so a meter projection is needed
* 187999 is known to all spatialite Databases
   * and thus RasterLite2
* all srid >= 40000 are consider user defined
   * so will cause no conflict
* it does not matter which meter projection is used 
   * but since there are 2 (or 3) functions that used it
      * these function **must** use the same
         * this the use in LibraryConstants

**Comment by moovida** [comment]
Closing this, discussion has been going on in the pull request
