### ISSUE TITLE
"ERROR: null" when trying to draw polygon. Version 4.4

### ISSUE THREAD

**Issue by betrieb** [geopaparazzi/geopaparazzi#283]
In edit mode trying to draw a polygon I always get "ERROR: null"

Details:
Steps I took to generate this issue:
In "Import" I created a new "Default Database".
Then I closed and re-opened the app.
Under "Spatialite data list" I only checked the "polygon" entry.
In map view I pressed the edit button.
When trying to draw a polygon i keep getting the error, regardless oh how i try to draw it, crossing lines, no crossing touching first and last note or leaving it open.
I tried closing and reopening the app, tried with GPS on/off.

**Comment by moovida** [comment]
Hi, I tried step by step the workflow but wasn't able to reproduce the problem.

Do you have any more info?

Can you look into the secret view and log to see if there are errors?

**Comment by betrieb** [comment]
Thanks for your quick reply.
There are errors, I took a screenshot from the log:
![screenshot_2015-07-26-00-23-52](https://cloud.githubusercontent.com/assets/4226042/8891515/6f27741c-332d-11e5-8dc9-62172cd2d055.png)

Otherwise I'm using a Fairphone with Android 4.2.2
Not sure what info I could provide else?

**Comment by moovida** [comment]
Ha, I need to add a *send log by email" button, true, true :-)
Ok, this is giving a nice error, but it is related to the cutout tool, not to the polygon creation.

Can you try to remove the imported default database, delete the log and start again. try to create a polygon and then send me the error just of that action? That might help to get started.

**Comment by betrieb** [comment]
I just figured I tried the wrong thing to create a polygon. Now figured out how to create a polygon and it is working fine. Sorry for the inconvenience.

**Comment by moovida** [comment]
Hi, I will leave this open to fix this. Even if the wrong tool was used, it should not give an error as it does.

**Comment by mj10777** [comment]
Also it would be nice if both of these step could be explained again
* so that we can if the document needs to be clearer
   * I just figured I tried the wrong thing to create a polygon. 
   * Now figured out how to create a polygon and it is working fine.

**Comment by moovida** [comment]
The documentation is in progress right now. The more advanced features always come last I am afraid. But it is in the todo list.

**Comment by mj10777** [comment]
Yes, that is often the case

**Comment by moovida** [comment]
fixed
