### ISSUE TITLE
gpslog removed even though log has many points

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#288]
This just happened to me this weekend. I was using the log function and the GPS log was working great. When beginning a new log I used the "continue from previous" checkbox. The log showed up on the map. At the end of two days, with a very long log with many many points, I had the log off and was just navigating on the map (browsing the map) and ... poof ... suddenly the log disappeared. In looking at the tables, there does not seem to be any corruption, but the logs definitely were deleted from both the gpslogs, gpslogsdata, and gpslogsproperties tables.  And here are some records from the log table (note I have four older logs, so this one that had two days of log data was logid 5) (
![logtable](https://cloud.githubusercontent.com/assets/6129193/9849789/f3b69d10-5abb-11e5-8491-04f6c67e25ac.png)
:

If the screenshot doesn't come through, the key record is: "Removing gpslog; since too few points were added. Logid:5"
thoughts?

**Comment by mj10777** [comment]
Any idea about the amount of records that could have existed at this point?

>> since too few points were added
* the amount could have overflowed the container of the counter (integer= 2.147.483.647)
   * 2.147.483.647+1 could cause this error

**Comment by tghoward** [comment]
That may be possible, but I had already stopped the track. Logging was off.
But it was perhaps 15 hours of logging.  While I was just panning the map,
just before the track was deleted, it DID pop up a message ... that I
didn't read carefully but I think it had something to do with starting
another log ... which I did NOT request.

**Comment by mj10777** [comment]
Looking at the code
* after restarting an existing log
   * the count of the log is **not** retrieved
      * currentPointsNum = 0;
* and something ends the logging
   * `it DID pop up a message`

The the condition to delete the log would be fulfilled
* currentPointsNum < 4

---
To be determined:
* what caused the the log end

Something that might avoid this problem
* set currentPointsNum to the existing number of records
   * when continuing the log

**Comment by moovida** [comment]
Outch, this is bad and @mj10777 nailed for sure the fact right that it needs to make sure that the log is not a continued log. I will have to check this, since I was quite sure that the number would be taken from the previous log.

I will check into this.

**Comment by mj10777** [comment]
If continueLastLog > 0
 then there a more than 3 records

so

if ((currentPointsNum < 4) && (continueLastLog < 1))

should resolve this.

**Comment by moovida** [comment]
Fixed in 117318c
