### ISSUE TITLE
Additional zoom capabilities for hi-res screens

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#291]
Enhancement request:
As screens continue to increase in resolution, the ability to read text and see detail at the specified zoom continues to be a problem.  _Also_, file size increases considerably when storing tiles at the higher resolutions (19, 20...).  

It would be GREAT to be able to zoom in and out a little bit while keeping the basemap zoom resolution the same. Perhaps a small, single button next to the current zoom buttons that permits the user to toggle among a few (3 or 5?) zoom (resolution?) levels. 

For example. If I have a locally stored mbtiles database that only has tiles up to zoom level 18, when I try to zoom to 19, the screen goes blank. It would be great to have a way to 'zoom in' on zoom level 18 .. essentially showing less of the landscape and a slightly more pixelated basemap, but increasing the resolution on all sqlite (vector) data.

Thanks for considering this.

**Comment by moovida** [comment]
While I really like this idea, I have no idea where this should be implemented. But I will investigate. 
This should be done for any tile based source, since often there are narrow vector data overlayed and one is not able to see them, because the zoom level ends.

The splitting and zooming of the tile should not be the issues, since it is just a quarter each time.

If in the meantime someone comes up with some implementation ideas, just add them here or to a pull request.

**Comment by mj10777** [comment]
This, of course, would eat up resources while running and could them become very slow.

But basically, the code in the mbtiles class, has what would be needed to implement this
* `android.graphics.*`

(many,many hours later)

I am working on a possibility for this from inside mbtiles
* so maybe tomorrow some results

**Comment by moovida** [comment]
Are you sure @mj10777 ?
I am not so pessimistic. What needs to be done is to take the tile at the previous zoomlevel, cut a quarter and scale it (and if we want, cache it). Why do you think this will be particularly heavy? 
I would like to have this for any tile source, not just mbtiles.
This is something that also webbing clients like openlayers and leaflet have and use. Off my memory I do not remember the name, but it is something like virtualzoom, which is a second max zoomlevel.

**Comment by mj10777** [comment]
You mean the first part I assume.
* for the first zoom_level that won*t be a big problem
   * that is what I am doing now

But lower down (more that 1 level)
* you will have to find that last supported
  * scale/split
     * scale/split
        * etc. until you have the right one

And that for every tile.

**Comment by moovida** [comment]
I assume that with some math one should be able to cut out the proper portion of the tile even if some zoomlevels have been *jumped* (without the need to scale/split many times... i.e. you scale/split just once). But I agree that most probably each zoomlevel is passed.

**Comment by tghoward** [comment]
For the gui side, I thought of one possible implementation last night. Imagine a user long-presses the zoom number ("18") at the lower-right in map view to "lock" the current zoom level. The number then turns a different color (red?). When locked, then the + and - buttons would then allow the secondary scaling within that zoom level.

**Comment by mj10777** [comment]
I have created some extra functions in MBTilesDroidSpitter
* where the main Tile retrievement and basic static functions exists

Goal:
* when a Tile is not in the Database `getTileAsBytes`
  * a check is done if the previous tile (in the Zoom-Levels) exists
     * a calculation which Tile this is and the position (0,1,2,3) 
        * `fetchTilePrevZoom`
     * the Tile retrieved (when it exists) `fetchBitmapTilePrevZoom`
        * rescaled `resizeBitmap`
        * split into 4 Tiles `arrayResizedBitmap`
          * but with a parameter that **only** a specific tile is returned
             * (0,1,2,3) = NW,NE,SW,SE

* `getTileAsBytes`
   * then returns this tile

---
Demo:
* this mbtiles has `gaps` within a Zoom-Level

![20150918 without_tile_scale](https://cloud.githubusercontent.com/assets/4899405/9976115/1584abfa-5ed9-11e5-8526-ada00732e398.png)

* using this functionality 
   * the area looks like this:

![20150919 with_tile_scale](https://cloud.githubusercontent.com/assets/4899405/9976118/50661358-5ed9-11e5-8511-817829636741.png)


---
At the moment (this was basically for testing)
* only the first level missing is resolved

My impression is speed wise
* as if a tiles is being downloaded

**Comment by moovida** [comment]
What is the state of this issue?

**Comment by moovida** [comment]
this should be solved with issue #351
