### ISSUE TITLE
New custom form entry not cancel

### ISSUE THREAD

**Issue by picaosgeo** [geopaparazzi/geopaparazzi#296]
When new custom form input from MapView or Note

Steps as follows,
1) Tap MapView
2) Tap Note
3) Tap custom form
4) Nothing to do and press cancel icon [X]
5) Back to MapView then note icon created in the map.

**Comment by moovida** [comment]
Thanks @picaosgeo , this is a known bug (by me) that I never fixed. I will try to do so for the next release. :-)

**Comment by moovida** [comment]
fixed
