### ISSUE TITLE
Show map without GPS

### ISSUE THREAD

**Issue by Matthias84** [geopaparazzi/geopaparazzi#304]
If you are just online via wifi and don't get / want GPS acquired GP freezes, as it seems to require the current position. Instead it could calculate the bbox center / centeroid of all existing notes and display all of them on the map.

**Comment by tghoward** [comment]
Matthias,
You might have to be more specific. I regularly use Geopaparazzi with no
GPS signal and it works just fine for me. I don't think I've seen any
issues with it freezing under this circumstance.  There is actually an
alternative location collection system already -- using the red crosshairs
in the middle of the map.
Cheers,
Tim

**Comment by Matthias84** [comment]
Hi Tim, thank you for your response! This is pretty strange, so let's try to debug it.

I use the Geopaparazzi 3.3.0 f-droid build. If I start the app without GPS, I get asketd to activate it. If I cancel that dialog, I can proceed. Then I enter the map view and sometimes it displays the map with items, but freezes ('Geopaparazzi has to be stopped') and sometimes it just freezes. :cry:

**Comment by mj10777** [comment]
You get asked to activate the GPS?
* can you give a title of the dialog?
   * it would be needed to look further into this

Normally the application can be started without GPS
* if you try to start tracking, without GPS
   * that will bring a message and fail to start
      * it has never freezed with me under such conditions (i.e. after continuing in the map-view)

**Comment by tghoward** [comment]
Hi Matthias,
I installed Geopaparazzi 3.9.8 directly from the Play Store, turned GPS
off, started Geopaparazzi. I got the dialog you mention ("Your gps is
disabled! Would you like to enable it?"), I clicked "Cancel" and then went
to the map. It worked fine for me. I could pan, zoom, view the map, and
place bookmarks.   I am using an older Nexus 5 with Android 6.0.1.

Ideally, you should be using the latest version, which is 4.4. If for some
reason version 3 has to be used, you should use its most recent version
(3.9.8). I don't know why f-droid does not use the most recent version of
its applications. It seems that the build it is using it unstable. Can you
get f-droid to update the version they are using? That would be the best
course of action.
Tim

**Comment by Matthias84** [comment]
@tghoward Thank you for the details, I will try to ping f-droid for an update

**Comment by moovida** [comment]
I am closing this here. Discussion about inclusion in f-droid is welcome in the mailinglist, or the dedicated issue.
