### ISSUE TITLE
Support open311 Georeport v2 ?

### ISSUE THREAD

**Issue by Matthias84** [geopaparazzi/geopaparazzi#305]
I'm wondering, if there are any plans to add support to the [Open311](http://www.open311.org/) protocol? This is an general standard for civic participation and city issue reporting and currently the [lack of resources](http://lists.open311.org/groups/discuss/messages/topic/6IBcetLMx6WXGtniLKXkf9/) to keep their Android app up-to-date. Most of the functionality of GP seem to be quite similar to their approach.

**Comment by moovida** [comment]
Hi @Matthias84 , the second link doesn't work. 
The idea is interesting, but this is a big one to maintain, maybe even to implement.

They used to have an android app? So there is already code for that, right? Open Source I assume?

**Comment by moovida** [comment]
I found a thread telling that Milo is currently upgrading the app. You mean the on from Indiana, right?
It still is an interesting project, I will look into it.

**Comment by moovida** [comment]
This has been stalling too long. Closing it. Feel free to open it again, is necessary.
