### ISSUE TITLE
AirDroid Application over WiFi

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#308]
You may find this interesting
- runs with a WiFi connection

You cannot actually run an application from the interface
* but you can observe the Application running 
   * and create a screen shot

There seem to be many functions to interact with
* Contacts
* Notifications
* Up/Download files
* Backup and Restore Data/Applications

https://www.airdroid.com/en/

**Comment by moovida** [comment]
Hi @mj10777 , airdroid is indeed an interesting app and also my favorite one for file transfers. It has even saved me when doing courses and the usb connections didn't work to download surveyed databases. We always suggest Airdroid in those cases. Nice nice!
