### ISSUE TITLE
httpS tileserver

### ISSUE THREAD

**Issue by gonzalolopezgarcia** [geopaparazzi/geopaparazzi#316]
this tile server don't work correctly: https://ts0.larioja.org/mb.php?z={z}&x={x}&y={y}
may be, because it is an httpS service?

Standart execution: https://ts0.larioja.org/mb.php?z=9&x=252&y=189 is ok!
but this tile service configuration don't run:
  url=https://ts0.larioja.org/mb.php?z=ZZZ&x=XXX&y=YYY
  minzoom=0
  maxzoom=19
  center=-2.45 42.46
  type=google
  format=png
  defaultzoom=13
  mbtiles=defaulttiles/iderioja_mapabase.mbtiles
  description=IDErioja MapaBase EPSG:3857  2016 IDErioja D.G.Catastro OSM contributors

**Comment by moovida** [comment]
Hi @gonzalolopezgarcia , I solved this longstanding bug and I thought I put it in the release.

Since I have some stuff to do also for the rasterlite part, I will see to send you the fix asap.

**Comment by moovida** [comment]
fixed

**Comment by gonzalolopezgarcia** [comment]
Great!
I like very much Geopaparazzi and I'm thinking about translate to Spanish the documentation of the new release when it is ready.
GonZaLo

Enviado desde Yahoo Mail con Android 
 
  El mié. 25 25e may. 25e 2016 a las 21:36, Andrea Antonello<notifications@github.com> escribió:   
Closed #316.
