### ISSUE TITLE
Images taken within Geopaparazzi are not geotagged (in exif information)

### ISSUE THREAD

**Issue by RW-gis** [geopaparazzi/geopaparazzi#326]
It is helpful when surveying that the smartphone records the photograph location in the exif information for the photograph. This is helpful even if Geopaparazzi also records the location. I think that currently when I take a  photo from within Geopaparazzi no gps information is recorded in the photo's own exif information.
I have only tested this once, and quickly.
I'm using a Moto G Android smartphone with the standard camera application. I also took photographs outside of Geopaparazzi (same time, same location) and the geotagging information is present in the exif information.
(Version 4.4 from Google Play)

**Comment by moovida** [comment]
THis has been verified by another user, so it seems that we lost that information along the way, most probably due to some scaling issues. 
Will need to check this.

**Comment by moovida** [comment]
Useful info from Brent: 
```
  I had a quick look at the code (ImageUtilities.java).  It looks like the original jpg is read then converted to a bitmap, for storage in the database when called by AddNotesActivity.java, and in the process the EXIF tags are stripped. 
 
  Would it be better just to store the original jpg "as-is" in the database?  Or perhaps get the EXIF tags, do any rotation needed to compensate for the orientation of the camera,and add the EXIF tags back in to the new jpg before placing in the database.
 
And perhaps add additional EXIF tags for direction of image (Exif.GPSInfo.GPSImgDirection, Exif.GPSInfo.GPSImgDirectionRef?)
 
In a perfect world there would be tags for roll, pitch, yaw...

```

**Comment by RW-gis** [comment]
Good :+1: 
This has been a determining factor in not using Geopaparazzi in the past.
