### ISSUE TITLE
Problem accessing basemaps on SDcard

### ISSUE THREAD

**Issue by silviafranceschi** [geopaparazzi/geopaparazzi#338]
When a background file (MBtiles) is selected on the the SD card, the application gives this error “The selected file is not supported as basemap”.
The same file copied in the local memory works perfectly.

**Comment by moovida** [comment]
This is confirmed. The sdcard doesn't accept the db to be opened in rw mode, even if then it is only read.

**Comment by moovida** [comment]
fixed
