### ISSUE TITLE
Set default map scale factor

### ISSUE THREAD

**Issue by MB1965** [geopaparazzi/geopaparazzi#351]
My topic is somehow related to #291, but I suggest a different approach.

I use offline mapsforge maps and also MBTiles maps created with MOBAC on a 5" 1440x2560 screen. Especially with MBTiles maps, everything is so tiny that it is hardly usable. 

I think a good solution would be to allow the user to make a choice between overview and detail by adding a default map scale factor (e.g. 100/150/200%) option to Geopaparazzi, like Oruxmaps does it (Settings | Maps | Standard-Zoom). This way everybody can easily adjust the appearance of the map to his devices screen.

![geopap](https://cloud.githubusercontent.com/assets/22999651/19620463/33856ad8-987e-11e6-8cad-51b5e0040400.jpg)

![factor100](https://cloud.githubusercontent.com/assets/22999651/19620327/951f4f50-987b-11e6-8534-8d7004fea0c8.jpg)

![factor200](https://cloud.githubusercontent.com/assets/22999651/19620333/a932e3ee-987b-11e6-972e-452d69233662.jpg)

I think this works in a way that after reading tiles from database, each tile is scaled by the desired factor (if not 100%) and then drawn on the map.

What do you think? Is this possible?

**Comment by moovida** [comment]
Hi, I am not sure I understand. In your screenshot you are zooming the same image? Or is it pulling another zoomlevel?

**Comment by MB1965** [comment]
All three screenshots use the same zoomlevel (11) from the MBtiles database. For the last one Oruxmaps just does bitmap upscaling afterwards ("200" indicates magnification by factor 2). You can see that the image is a bit blurry, but in my opinion it's still better to use than the 100% view, because you can at least read village names.

**Comment by moovida** [comment]
That is interesting, since the 3 screenshots didn't look very blurry to me :-) 
So I agree that this is a nice feature. I will mark this as a new feature. I will sure work on this as soon as I have some time.

**Comment by tghoward** [comment]
I think this would be an excellent addition, but I am worried that if the setting (magnification factor) is buried down in settings somewhere it would be less use useful. If bitmap upscaling is easy to do by the app, perhaps it could be made more accessible to users who might want to change the scaling factor in 'real time'? I agree with the Oruxmaps example you might always want to read the village names, but for aerial imagery, for example, you might want to see more of the landscape at zoom 11, but then also see details in a smaller area (again at zoom 11).

**Comment by MB1965** [comment]
Maybe it could be done like this: 

Put default scale factor in settings menu, which will be applied every time the app starts, and which is mainly there to adapt the mapview to screen DPI. 

And then let user use "pinch to zoom" gesture to lock in a new scale factor (maybe snap to multiples of 50%), until changed again or app closes.

**Comment by moovida** [comment]
I have implemented this.... the following way.

The zoom in and out buttons now listen to a longclick. The + button on long click will double the scale of the mapview. The - button half it.

The app keeps the scale in memory until the exit. Once started again, one has to set the scale again. Since this is a quick thing, I see no problems.

I have tested this a bit and it seems to work nicely, but I still have to make some tests while collecting data and logs. 

If someone is able to compile everything, I have pushed these changes already. It would be nice to have some testing.

**Comment by tghoward** [comment]
Excellent!  Thank you, this sounds like a good solution.  I will test it out, hopefully this weekend.

**Comment by moovida** [comment]
Fantastic @tghoward , thanks!

**Comment by tghoward** [comment]
I tested this and I really like it! Looks great!

**Comment by MB1965** [comment]
I like the implementation with Longlick.

I did some testing and found the following issues. When scaled ...
- the distance measurement tool shows incorrect values (e.g. 2x the real distance when scaled to 200%)
- when you want to move the map, the threshold (how much you have to move your finger until the maps starts moving) increases with the scalefactor
- the same appplies for the threshold of the pinch to zoom gesture

The issue with the tresholds becomes noticable at 400% and at higher zoom factors it really becomes a problem.
Maybe this doesn't matter so much when someone uses this feature to quickly zoom in to see something better and then zoom back to 100% again, but for users who have a High DPI device and want to stay in 200% or 400% all the time, it would be good if this was fixed.
