### ISSUE TITLE
Photos are not rotated in QGIS

### ISSUE THREAD

**Issue by luca76** [geopaparazzi/geopaparazzi#352]
Hi,

when I import the project in QGIS (with the plugin "ExportGeopaparazzi", the photos do not follow the right orientation.

There's a way to fix this problem?

Thank you!

**Comment by moovida** [comment]
Hi Luca, I am afraid this is not the right place for this issue. We are not the authors of the QGIS plugin and  would not know where to start. Maybe the QGIS issue tracker is a better place. Sorry.
