### ISSUE TITLE
Unable to add mapurl on Android 6

### ISSUE THREAD

**Issue by luca76** [geopaparazzi/geopaparazzi#361]
Hi,

my friend has a samsung phone with Android 6. When he is going on Select Source, the strange thing is that he cannot see the "+" (plus) icon at bottom-right of the screen to add mapurl source. Therefore, he is forced to use the Geopaparazzi3 in order to be able to see an orto-photo.

Another friend with a galaxy note 4 can see the plus icon.

**Comment by luca76** [comment]
could I suggest you to add a menu with "add source" as fallback?

**Comment by moovida** [comment]
Hi, could you attach a screenshot showing the problem? 
If it is not necessary, then an additional "add source" is not something I would want to add. If I am able to reproduce the problem and fix it, it would be better.

**Comment by luca76** [comment]
![geopaparazzi_problem](https://cloud.githubusercontent.com/assets/5095918/20261946/59b089f6-aa60-11e6-9135-bd750eb95f1e.png)
![geopaparazzi_note4](https://cloud.githubusercontent.com/assets/5095918/20261947/59b4c35e-aa60-11e6-8920-878f2b2ff12d.jpg)

**Comment by luca76** [comment]
As you can see, the first image is without the " + " icon and the second is from note 4.

**Comment by moovida** [comment]
Hi @luca76 , I have thought about this and I found only one possible reason for this.Is it possible that he installed the geoss2go app which configures geopaparazzi? I tried on mine and if I create a profile in geoss2go that has no basemaps, what I then see in geopap is exactly the problem you mention.

**Comment by luca76** [comment]
No, I don't have geoss2go app installed.

**Comment by moovida** [comment]
:-( you mean your friend ("my friend has a samsung phone with Android 6")? Or you also don't see it?
What is the device?

And does something change when you change orentation?

**Comment by luca76** [comment]
sorry, my friend is not a "real" friend :-) he was a researcher and I don't even see him anymore :-(

**Comment by moovida** [comment]
Hi @luca76 , could you please test if this still happens?

**Comment by luca76** [comment]
Sorry I cannot test anymore because I will not see my "friend" (not in
reality...)

Il 06/giu/2017 17:32, "Andrea Antonello" <notifications@github.com> ha
scritto:

Hi @luca76 <https://github.com/luca76> , could you please test if this
still happens?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/geopaparazzi/geopaparazzi/issues/361#issuecomment-306524308>,
or mute the thread

**Comment by moovida** [comment]
ok thanks @luca76 . For now I will close this issue then. If it happens again we can always reopen it.
