### ISSUE TITLE
Spatialite 4.4.0 - preperations

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#371]
Sandro is (again) busy with the testing of the Topology logic
* together with the people from the Tuscany Region
   * it seems there are still precision problems due to the excessive use of floats instead of doubles

He is, however, preparing a release.

A major change will be the replacement of
* liblwgeom with [RT Topology Library - librttopo](https://git.osgeo.org/gogs/rttopo/librttopo)

All functions listed here:
* [Spatialite LWGEOM features](http://www.gaia-gis.it/gaia-sins/spatialite-sql-latest.html#p14d)

will be made available in **librttopo**
* which can be compiled for android, such as 
    * MakeValid(), Split(),Snap(), Node(), SelfIntersection()

2 sql-functions will be removed:
* HasLwGeom()
* lwgeom_version()

and replaced with a corresponding librttopo version:
* HasRtTopo()
* rttopo_version()

**HasLwGeom()** is being used in geopaparazzi
* DatabaseCreationAndProperties.getSpatialiteProperties
   * and must be replaced with **HasRtTopo()** before a new library version can be used

---
In the last few days I have updated the [libjsqlite-spatialite-android](https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki) project
* that supports the latest (committed) spatialite version
* newest GEOS and PROJ.4
* latest librttopo

This version works well with my version of Geopaparazzi, which is still based on 4.3.0
* with RasterLite2
(I never got the 5.0.1 version to work correctly)

I would suggest trying out the compile libraries, that can be download from the above link.

**Comment by mj10777** [comment]
I have just attempted to compile the latest master.

For the first time the update of gradle failed
* after calling 'android update sdk'
For:
* geopaparazzi:geopaparazzispatialitelibrary:unspecified
* geopaparazzi:geopaparazzimapsforge:unspecified
* geopaparazzi:geopaparazzimarkerslib:unspecified

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':geopaparazzi.app'.
> Could not resolve all dependencies for configuration ':geopaparazzi.app:_debugApk'.
   > A problem occurred configuring project ':geopaparazzimarkerslib'.
      > Could not resolve all dependencies for configuration ':geopaparazzimarkerslib:classpath'.
         > Could not find com.android.tools.build:gradle:2.2.3.
           Searched in the following locations:
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
               https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
           Required by:
               geopaparazzi:geopaparazzimarkerslib:unspecified
`
Resolved with:
* [based on the solution found here](https://code.google.com/p/android/issues/detail?id=229673)

Adding after 'mavenCentral()' in 'build.gradle' for the 3 projects:

```bash
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
    }
```

after which the project compiled
* creating a 'GeoPaparazzi_5.1.2.apk'

I have no idea if the is the correct way to deal with this.

**Comment by mj10777** [comment]
I have just spent the last hour attempting to get 'GeoPaparazzi_5.1.2.apk' running
* I can see the geometries, but cannot filter them in the list

I could filter between Table/Views

Also all of them seem to be set to on
* and no way to turn all off [I have 133 views]
   * so I can turn on what I need

Nothing is shown in the map
* busy rendering the 133 Views?

Could not load an RasterLite2 Database
* set to on
   * will no go into the directory containing the files (extension '.db')

No reaction when selecting a mbtiles file.

Since I use RasterLite2 to 99%
* which I cannot load
* and can see no geometries
I cannot say if the new library works.

I truly wish that the MapsDirectory logic
* which found what was supported
   * hunting through the sdcard for what one needs
would again be an option for those that want it.

**Comment by moovida** [comment]
Hi @mj10777 , I am abroad at the moment, but for next week I have planned work on geopaparazzi and maybe even a review. If you are available next week we can plan some discussion to get back the loading of a complete folder (as additional to what is there already) and check why some of the stuff doesn't work for you. Let me know if you have days you are not around, so that I will try to do this work when you are also available.

**Comment by mj10777** [comment]
Sorry, I forgot to reply to  this ...

For the next few day up to 12h is ok
* an estimated start time beforehand would be appreciated

**Comment by moovida** [comment]
Hi @mj10777 , since I didn't hear anything I decided to move this to the next week. 
I am doing minor changes because I am not working on releasing the plugins for gvSIG. So would next week also be ok? It would be good to have some tentative days.

**Comment by mj10777** [comment]
At the moment, I am fine with almost any day up to 12h.
* at some point I will become busy - but that depends on others when it will start

**Comment by moovida** [comment]
Just to let you know that I am here working on this. If you want to send me some mbtiles and rasterlite2 db that do not work, please do so, I will test them.

**Comment by mj10777** [comment]
I believe that the problem is that the extestion '.db' is not being looked for
* when searching for RasterLite2 Databases

mbtiles works correctly

**Comment by moovida** [comment]
```
I can see the geometries, but cannot filter them in the list
I could filter between Table/Views
```

This can be done with the checkbox in the upper right sight of the Spatialite Databases view. Still has view and Table.

```
Also all of them seem to be set to on

and no way to turn all off [I have 133 views]
so I can turn on what I need
Nothing is shown in the map

busy rendering the 133 Views?
```

yeah, right now each has to be unchecked one by one. Can you please open an issue for that? I am going through all the bugs and I should have time to think about this also tomorrow.

```
Could not load an RasterLite2 Database

set to on
will no go into the directory containing the files (extension '.db')
```

Ok, I added that one back now. 

```
No reaction when selecting a mbtiles file.

Since I use RasterLite2 to 99%

which I cannot load
and can see no geometries
I cannot say if the new library works.
```

If you pull now, you will be able again. 
Anyways I tested it and all workes like a charm. Thanks for the updated libs!!

```
I truly wish that the MapsDirectory logic

which found what was supported
hunting through the sdcard for what one needs
would again be an option for those that want it.
```

I will add a load folder option to the tiles and spatialite datasets, that should work right? You select a folder and it browser and adds whatever it is able to.

**Comment by mj10777** [comment]
> I will add a load folder option to the tiles and spatialite datasets, that should work right? You select a folder and it browser and adds whatever it is able to.
Also for sub-folders?
> yeah, right now each has to be unchecked one by one. 
Why not just set it to off and then let the uset set what he wants to one
* views are mostly sub-sets, so turning everything on defeats the purpose

**Comment by moovida** [comment]
> Also for sub-folders?

yes, that would be the idea.

> Why not just set it to off and then let the uset set what he wants to one

That makes sense indeed. I will do that right now, it is a simple fix.

**Comment by mj10777** [comment]
Good, tell me when that is completed or tomorrow more likly
* then I will make a pull and try again

**Comment by moovida** [comment]
Ok, it is done. Try it out when you have time.
Closing this here for now, should be all sorted out.

**Comment by mj10777** [comment]
This version compiled without problem.

The Databases are now found and can be loaded (RasterLite2).

The directory functions work well and are swift.
* existing entries are still checked and must be turned off manually
* new entries are not checked as desired

---

Two problems have been noted:
* the tables are not sorted
   * **VECTOR_LAYERS_QUERY_EXTENT_VALID_V4**
      * sorts these by type and name
* the filtering no longer seems to work
   * as far as I remember it worked before
      * **berlin_streets_** showed only those results starting with 'berlin_streets_'
        * but now nothing changes
