### ISSUE TITLE
very minor improvement suggestions

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#386]
In the newest version (5.2.0):
After choosing a basemap, there is no indication which one is on. It would be very nice to have a checkmark or highlight or  bold or some other way to know which basemap is activated. I *really* like the way the spatiallite layers work with the checkbox and layer sorting (order of drawing) .. very nice!

When choosing a folder to add to basemaps or to add to spatiallite list, it is a little odd to: 1. touch a folder, 2. it opens, and looks empty, 3. click check button to use the "empty" folder, 4. all the layers (basemaps or spatiallite layers) appear in your list. 

The odd part is that you choose the folder to go into it (#2), but then the contents of the folder are not displayed. You have to know that you have spatial data in the folder. Is there a way to preview what you will be adding?

Otherwise, excellent update!

**Comment by moovida** [comment]
Thanks for the valuable suggestions, I will keep them in mind.

**Comment by moovida** [comment]
Added
