### ISSUE TITLE
Suggestion for improving bitmap loading

### ISSUE THREAD

**Issue by struggggle** [geopaparazzi/geopaparazzi#387]
Dear developers,
I found two operations of bitmap displaying that can be optimized in geopaparazzi. 

When loading an image, Google suggests us to resize the image before decoding them. 
https://developer.android.com/training/displaying-bitmaps/load-bitmap.html
it works like this:

_public static Bitmap decodeSampledBitmapFromResource(Resources res, int resId,
        int reqWidth, int reqHeight) {
    // First decode with inJustDecodeBounds=true to check dimensions
    final BitmapFactory.Options options = new BitmapFactory.Options();
    options.inJustDecodeBounds = true;
    BitmapFactory.decodeResource(res, resId, options);
   // Calculate inSampleSize
    options.inSampleSize = calculateInSampleSize(options, reqWidth, reqHeight);
    // Decode bitmap with inSampleSize set
    options.inJustDecodeBounds = false;
    return BitmapFactory.decodeResource(res, resId, options);
}_

However, I noticed that in the following code, images are decoded directly without resizing: 

eu.geopaparazzi.mapsforge.databasehandlers.core.CustomTileDownloader.java   executeJob()   (line 798)
https://github.com/geopaparazzi/geopaparazzi/blob/master/geopaparazzimapsforge/src/eu/geopaparazzi/mapsforge/databasehandlers/core/CustomTileDownloader.java

eu.geopaparazzi.library.network. NetworkUtilities.java     downloadBitmap()   (line 741)
https://github.com/geopaparazzi/geopaparazzi/blob/master/geopaparazzilibrary/src/main/java/eu/geopaparazzi/library/network/NetworkUtilities.java

In the above code, the images to be downloaded are from the internet, which means they are likely to be larger than required or very large. For possible large images, resizing them before decoding is very necessary. 

Do you think not perform image resizing will affect geopaparazzi's performance? If yes, perhaps checking and resizing the images before decoding them can help make app more smooth in user interaction (reduce memory consumption).

Looking forward to your response and hope I can help improve geopaparazzi.
Thanks.

**Comment by moovida** [comment]
Hi, I will check this, though I am quite sure that the images downloaded are exactly of the size we then use them. Nothing bigger is downloaded.

**Comment by moovida** [comment]
Closing, since no feedback.
