### ISSUE TITLE
add wms_nww as a git submodule

### ISSUE THREAD

**Issue by legrostdg** [geopaparazzi/geopaparazzi#391]
I see here https://github.com/geopaparazzi/geopaparazzi/pull/312#issuecomment-210474232 that `wms_nww` should be present at the root of `geopaparazzi` for the build to succeed. Would it be possible to add `wms_nww` as a git submodule, to reduce the manual overhead?

It would help having a newer `geopaparazzi` on f-droid: https://gitlab.com/fdroid/fdroiddata/issues/599#note_23328346

**Comment by moovida** [comment]
Hi @legrostdg , first off, I will do everything possible to support geopaparazzi in f-droid.

That said I am not sure what you mean.

Currently wms_nww needs to be in the same folder as the geopaparazzi one, i.e. they should share the same root folder:

```
├── geopaparazzi-git
│   ├── geopaparazzi.app
│   ├── geopaparazzi_core
│   ├── geopaparazzilibrary
│   ├── geopaparazzimapsforge
│   ├── geopaparazzimarkerslib
│   ├── geopaparazzispatialitelibrary
│   └── plugins
└── wms_nww
```

Is this the problem? I am not sure what a git submodule would do, never used it before.

PS: I never had the time to look at the complete procedure to get an app into f-droid, but would a package with the sources and one with the binaries be enough?

**Comment by legrostdg** [comment]
> PS: I never had the time to look at the complete procedure to get an app into f-droid, but would a package with the sources and one with the binaries be enough?

f-droid has to be able to build the source itself, so you don't have to provide the binaries. It helps if the build procedure is as simple as possible, though... So not having to remember to clone wms_nww in a specific place does help.

I would recommend to change the current directory structure to get something like this:

    ├── geopaparazzi-git
    │   ├── geopaparazzi.app
    │   ├── geopaparazzi_core
    │   ├── geopaparazzilibrary
    │   ├── geopaparazzimapsforge
    │   ├── geopaparazzimarkerslib
    │   ├── geopaparazzispatialitelibrary
    │   ├── plugins
    │   └── wms_nww (git submodule)

Like that you keep wms_nww in its own repo, and people just have to
`git clone --recursive https://github.com/geopaparazzi/geopaparazzi` and then build the package.

**Comment by moovida** [comment]
Hi @legrostdg , I liked the idea a lot and tried it out. It works well for me. 

Could you try that out to see if it is done properly please?

On a sidenote, for a external build I think you could also have troubles with the keystore file, which is not contained in the **geopaparazzi.app** folder as a file **ant.properties** and containes:

```
key.store=/path/to/your/file.keystore
key.store.password=pwd
key.alias=youralias
key.alias.password=aliaspwd
```

**Comment by legrostdg** [comment]
It seems great, thanks!

You may have a look (and maybe offer advice) there: https://gitlab.com/fdroid/fdroiddata/issues/599

**Comment by moovida** [comment]
@mj10777 , could you please have a look at the issues on F-Droid discussed here:
https://gitlab.com/fdroid/fdroiddata/issues/599

F-Droid is a Free and Open Source Android App Repository and it would be great to have geopaparazzi supported there. Right now the blocking thing it that they need to build the native libs from source and are asking if it is possible to do so in the build process. You think that is somehow possible?

**Comment by mj10777** [comment]
Everything is possible ...
* but to rebuild the libraries each time Geopaparrazi is build is not
   * it is very time consuming

A better solution would be 
* for this to be a separate project
   * to be rebuild when needed
      * and to then use the results

**Comment by moovida** [comment]
I agree with you. I am not sure what kind of build system is used for F-Droid. I will investigate, thanks.

**Comment by mj10777** [comment]
I have given an summery of the problems as I see it
* that may help in clarifying the situation

**Comment by moovida** [comment]
Fantastic @mj10777 , thanks. I will close this here.
