### ISSUE TITLE
Crash after enabling editing

### ISSUE THREAD

**Issue by dispiste** [geopaparazzi/geopaparazzi#393]
Geopaparazzi allows enabling the editing mode on a layer that is no longer available (because the Spatialite database has been removed from Geopaparazzi in the Spatialite Data List). This produces a Geopaparazzi crash when a new geometry is created and saved.

Steps to reproduce:
1- Load a Spatialite DB, make some layer visible, select this layer as the EditLayer and finally start edition
2- Finish edition and remove the Spatialite DB from Geopaparazzi
3- Start edition again. It should not be allowed, but it is, because the (non-existing) layer is still set as EditLayer
4- Add a new geometry and save
Result: Geopaparazzi crashes

It can be solved in 2 different ways:
- In SpatialiteSourcesMananger.removeSpatialite, we could set the EditLayer (on EditManager) to null if it is backed by the map we are removing. I think this is cleaner, but we don't have a way to know the table backing the ILayer (unless we cast to SpatialVectorTableLayer). Maybe we need a new method (getTable, getSource or similar) on ILayer??
- Another approach: checking if the layer is available before enabling editing. But we still lack the method on ILayer

**Comment by dispiste** [comment]
I've checking what is SpatialVectorTableLayer adding to SpatialVectorTable, and I believe it would make sense to make SpatialVectorTable implement ILayer, and just remove SpatialVectorTableLayer from Geopaparazzi. What do you think?

**Comment by moovida** [comment]
Merged your pull request. Thanks!
