### ISSUE TITLE
"Go to" misbehaving?

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#396]
In map view:
1. press orange menu button, upper right hand corner
2. press "Go to"
3. choose go to coordinate
4. Note default numbers are already populated (where is this?). And note that the numbers are written over grey text saying "longitude" and "latitude" making both hard to read. Is it possible to move the longitude and latitude labels?  I would prefer the default location to be your current location so if you don't have to go to far, you already have some of the numbers correct. Or have the previous location entered as the default location. 
5. [ the map had frozen at the location on me when trying earlier, but I can't replicate it right now, so I'll continue to try to replicate]

Thanks,
Tim

**Comment by moovida** [comment]
Hi @tghoward,
while I agree about the fact that it is not very elegant to have the coordinates hardcoded and fixed on my office (file is here: layout/fragment_dialog_insertcoordinate.xml), it is very useful for testing and I thought no one would use it :-)
I will probably keep it in a preference and make use of the last inserted. I leave this open here to remind me.

Regarding the layout I do not understand what is going on. Can you make a screenshot? Mine looks like this:

![goto](https://cloud.githubusercontent.com/assets/390250/26522455/55f64cbc-4301-11e7-9a39-c0f08752f74b.jpg)

**Comment by tghoward** [comment]
![screenshot_20170527-171529](https://cloud.githubusercontent.com/assets/6129193/26524443/651bf760-4300-11e7-85a3-028a7e2570e9.png)

Here's what it looks like on a Moto Z, (v. 5.2.0, as downloaded from play store). Same problem on a Nexus 5.

**Comment by tghoward** [comment]
Hi @moovida!
Thanks for thinking about this question. How about using the center of the map (cross hair) as the default go to location? Then a user can scroll on the map to a location, then choose "go to".

**Comment by tghoward** [comment]
Ak! No, my previous suggestion (immediately above) is dumb because that's all 'go to' does -- jump to a new location on the map. Sorry, I was temporarily mistaken about the usage! :)

**Comment by moovida** [comment]
Agh, that screenshot looks ugly. Not sure why this is happening...

**Comment by tghoward** [comment]
After upgrading, I can't reproduce that screenshot any more. The lat and lon labels are now above the fields. I'll re-open if it comes back!
