### ISSUE TITLE
wrong error message in choosing map or map folder?

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#403]
From the 'home screen', choose the layers icon to get to the basemaps list.
- choose "+" to add a new basemap
- choose a basemap that is *already* on the basemaps list
- you will get this error message: "The selected file is not supported as basemap:/ <full path here>"

but that map is supported and works just fine if you were to choose it from the existing basemaps list. 

Perhaps the error message could be "This map is already on the list maps to choose from"

Love the updates!
Tim

**Comment by moovida** [comment]
thanks for reporting. fixed in a3c8c79
