### ISSUE TITLE
Error on select basemap on android 5.0.1

### ISSUE THREAD

**Issue by fpsampayo** [geopaparazzi/geopaparazzi#404]
Hi, 

When push on add button to select new basemap, the app crashes. I test it on two different smartphones and only crashes on android 5.0.1. The other mobile has android 6.0.1 and works ok.

We update today from 5.1.2 to 5.3.1 and on the previous version we don´t had the error.

If you need more info please tell me.

**Comment by moovida** [comment]
Would you be able to send me an error log? Doesn't it propose to send the error via email when it happens?

**Comment by fpsampayo** [comment]
On app option "Analyze log" don´t show any error log, it only show info logs
When the app crashes, a popup show that an error occurs, but don´t propose nothing to send a mail, it only say that i sent you if i consider necesary.
Can you tell me where is, if it exist, the main log on mobile?

Thanks!

**Comment by moovida** [comment]
The main log doesn't seem to catch the problem that leads to the crash, I am afraid.

So it would be really important to be able to send the log via the popup that appears after the crash. Can you send a screenshot to see if I see something?

**Comment by fpsampayo** [comment]
Sure!

![screenshot_2017-06-06-17-01-42](https://cloud.githubusercontent.com/assets/912161/26836102/4119fa38-4ada-11e7-8f09-1a3ad1a7e37c.png)

**Comment by moovida** [comment]
And after that nothing happens? After this dialog usually the app to send the log is proposed to the user. 
It is very strange if that doesn't happen. I need that log to be sent to be able to understand the problem.

A long shot: can you try to uninstall geopaparazzi and install it again from scratch to see if then the app proposes to send the crash report?

**Comment by fpsampayo** [comment]
I've already tried before report this issue :-)

A note:
The app crash before the drop down blue buttons appear. On 5.2.0 without these drop down buttons, it don´t crashes.

**Comment by moovida** [comment]
I just checked on a 4.4.2 android and it works as expected. So it should not be a backward compatibility problem. 

I need to get that log :-) otherwise I am helpless. I do not have a 5.0.1 android. 

Would you be brave and try to use logcat to get me that log?

You should follow instructions like those here: https://android.gadgethacks.com/how-to/android-basics-capture-logcat-for-detailed-bug-reports-0167774/

**Comment by fpsampayo** [comment]
[logcat.txt](https://github.com/geopaparazzi/geopaparazzi/files/1055680/logcat.txt)

**Comment by moovida** [comment]
Fantastic @fpsampayo . Found the problem. It is an Android bug :-) 
But there is a workaround for it, which I will provide with the next release.

If you are interested, have a look here: https://stackoverflow.com/questions/33737192/android-vector-drawable-crash

**Comment by moovida** [comment]
fixed in changeset 3463cda

**Comment by fpsampayo** [comment]
Thanks @moovida!!
