### ISSUE TITLE
allow autocomplete or filtering with spinners on forms

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#411]
When working with long lists in combo boxes in a form the Android Spinner makes it pretty unwieldy. By this I mean that the user might have to scroll for many seconds to get to the desired item. Ideally, the user would be able to begin typing and the spinner would jump to the appropriate part in the list. See, for example, these discussions:

https://ux.stackexchange.com/questions/79113/android-spinner-with-many-items

https://stackoverflow.com/questions/18983484/combine-spinner-and-autocompletetextview

I'm most interested in the "connectedstringcombo" type where I have a full species list where Genus is the first field and Species is the second. I could send you a tags.json (16,000 lines) file if you would like to see how klunky it is. 

I can imagine two possible ways to implement. 

1. modify all the spinners to use AutoCompleteTextView (or something else). With short lists, behavior should be similar to currently, but with long lists the user should be able to filter by typing. One possible drawback is that AutoCompleteTextView might allow typing that is not on the list. 

2. create a new set of field types, perhaps called "longconnectedstringcombo" and "longstringcombo" that allows filtering or jumping to list sections by typing. 

Thanks for considering this. I've looked at the code and I don't think I have the ability to make the changes and submit a PR myself. And of course, I don't know which approach you prefer. 
Tim

**Comment by moovida** [comment]
Hi @tghoward , I like the idea a lot. I am not sure when I will be able to integrate it, but I will sure consider it for my next development round. Would it be possible for you to attach to the issue such a huge tags.json file that you mentioned? It would be good to have it for reference.

**Comment by tghoward** [comment]
@moovida , here's an example. See the field with key=genSpp in the "Taxon" form. (Obviously, change the filename to tags.json and place in the geopaparrazzi folder).  
[tags_longListExample.json.txt](https://github.com/geopaparazzi/geopaparazzi/files/1238933/tags_longListExample.json.txt)

**Comment by tghoward** [comment]
... And I was going to say, I'm glad you like the idea!

**Comment by moovida** [comment]
this has been solved. Working for 
```
autocompletestringcombo
```
and 

```
autocompleteconnectedstringcombo
```
