### ISSUE TITLE
Navigator in tile source does not navigate 

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#412]
I think there was some discussion on the google group about this but it is currently driving me crazy. Symptoms with a Moto Z, Android 7.0: Choose "Select tile source" . This is my screenshot:

![screenshot_20170805-132224](https://user-images.githubusercontent.com/6129193/28997432-ac31b7ca-79e2-11e7-885d-908455d300a5.png)

The problem is that I have .map files and other mapurl files in /storage/emulated/0/geopaparazzi. They do not display.   Next, choose orange plus button, Navigation (up arrow, upper right corner) allows me to rise one level then stops and does not allow any more navigation. I am stuck in the app's custom file system (eu.hydrologis.geopaprazzi/app_geopaparazzi) and can not get out! And this part of the file system is not visible to the user so I can't get around this problem by adding the .map file this folder.  Stuck!  Even changing the 'custom SD card path' does not allow me to navigate outside of the hidden app file space. 

![screenshot_20170805-132240](https://user-images.githubusercontent.com/6129193/28997400-9694e3f2-79e1-11e7-9f98-a46ecd429011.png)
The above screenshot shows the farthest I can go up, more tapping of the up icon does nothing.
Is this a Moto only problem?
Tim

**Comment by tghoward** [comment]
I also tried un-installing and re-installing geopaparazzi. No luck. The .map file (from openandromaps) does not become an option.

**Comment by moovida** [comment]
Closing this, since this is discussed in other issues. Will be done in #440
