### ISSUE TITLE
GUI: Larger buttons

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#427]
Small buttons are hard to see and press while on the trail.  While it can be difficult to show a lot of information on a small screen, where there is room, we should make the text and buttons larger.  For example:

![notes](https://user-images.githubusercontent.com/1638313/33445139-53c52ddc-d5b9-11e7-8a11-36e80ae65f7b.png)

**Comment by moovida** [comment]
See https://github.com/geopaparazzi/geopaparazzi/pull/429 for discussion. Closing this here for now.
