### ISSUE TITLE
GUI: Add dynamic text captions to Dashboard tiles.

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#430]
First time and casual users can be confused by the meaning of the tiles on the Dashboard.  It would be nice to have captions indicating the meaning of the tile and perhaps some feedback showing the result of the tile's action.  For example:

![dashboard](https://user-images.githubusercontent.com/1638313/33577313-d111faba-d8ff-11e7-9108-217fb72054b3.png)

**Comment by moovida** [comment]
I had this like you mention it (apart of the dynamic part for logs and notes, which seems nice), but it didn't result graphically correct on certain devices. The format of the screen sometimes eat up the text, resulting in an inconsistent behaviour. 

Therefore I then decided to put the information behind a tooltip (long tap on the tile) and that is how I still think it is best to have it. 

Did you know about the tooltip and is it not enough visible?

**Comment by brentfraser** [comment]
I wasn't aware of the long press.  While I think it is useful, it's too hidden for new users.  And it is not dynamic.  I think it is very useful to show the number of Notes Saved for example (I've had to emphasize using the little disk icon for saving notes).

Which devices had trouble with rending the text?

**Comment by moovida** [comment]
I have added the counts to the dynamic tooltip. 

I do not remember which devices, but when space became few, the first thing to disappear (sometimes also partially), was the text.
