### ISSUE TITLE
QIG data can not add to project

### ISSUE THREAD

**Issue by sunshine0576** [geopaparazzi/geopaparazzi#431]
I use QGIS to edite my data ,export as spatialite.
i put the spatialite file in my phone,i  add *.sqlite file to APP.

APP show "The selected file doesn't contain any vector data:" 

QGIS version:2.14.8

**Comment by brentfraser** [comment]
What is the result of using the "ogrinfo" command line on your spatialite file?

**Comment by brentfraser** [comment]
You may want to ask the question on the Geopaparazzi user list: https://groups.google.com/forum/#!forum/geopaparazzi-users

**Comment by mj10777** [comment]
Try using the 'Spatialite Recovery Mode':
* look for :
When Spatialite Recovery Mode is ON 

at:

https://github.com/geopaparazzi/Spatialite-Tasks-with-Sql-Scripts/wiki/checkDatabaseTypeAndValidity-geopaparazzi-specific

**Comment by moovida** [comment]
Closing this, since the user didn't report back.
