### ISSUE TITLE
MapviewActivity line  370 ，The state of "LeftButtoonsEnablement  " is wrong

### ISSUE THREAD

**Issue by sunshine0576** [geopaparazzi/geopaparazzi#432]
if (activeToolGroup != null) {
            toggleEditingButton.setImageDrawable(Compat.getDrawable(this, R.drawable.ic_mapview_toggle_editing_on_24dp));
            activeToolGroup.initUI();
            setLeftButtoonsEnablement(true);//
        }

 the steps of Reproduce
1.select a layer to edit
2.selectAllButton  (select some feature) 
3.FeaturePagerActivity，   **click ActionBar back**
4.LeftButtoonsEnablement and activeToolGroup   all show  on the screen

**Comment by moovida** [comment]
thanks for reporting this.

Fixed
