### ISSUE TITLE
GUI: Show values on settings screens

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#433]
It would be nice to see the current settings values in the "summary" field under the settings title so the users do not have to tap each setting to see the value.    For example the GPS settings could show the distance (10) under the title:

![settings](https://user-images.githubusercontent.com/1638313/34163913-4d9f38ae-e495-11e7-9e29-2b91b4358ac0.png)

**Comment by moovida** [comment]
I thought it would be simple, but there is some work behind this.

Where you thinking to do a pull request? :-) It would be indeed nifty.

**Comment by brentfraser** [comment]
Yep I've got a pull request in the making...

**Comment by moovida** [comment]
Thanks for the PR Brent! Closing this here.
