### ISSUE TITLE
Map providers

### ISSUE THREAD

**Issue by am2222** [geopaparazzi/geopaparazzi#439]
Hi,
I want to know how you have defined a data provider for spatialite to render those data on maps-forge. If I am right there is not any build-in data provider for maps-forge so there must be some data probiders. Is it possible to give me some tips to find the classes and related process? 
thanks very much

**Comment by moovida** [comment]
Hi @am2222 , I didn't look at the issues for a while and I assume it is no longer of use to you, but I will answer anyways.

The custom tiles based maps different from mapsforge (ex. mbtiles, wms...) use the following class to create tiles:
eu.geopaparazzi.mapsforge.databasehandlers.core.CustomTileDownloader

**Comment by am2222** [comment]
@moovida  thanks very much, It is great, I have another question about editing features of geopaparazzi such as shp editing or even better WFS editing, does geopaparazzi supports it?

**Comment by moovida** [comment]
I am afraid not. We have the possibility to do vector editing only on spatialite databases, btu the documentation about it is missing right now. 

But for spatialite databases you have simplified editing available both for geometries and attributes.

**Comment by am2222** [comment]
In fact my problem is perform editing in GUI I can send related post functions to wfs server or write to database. Can you help me finding related GUI which you have used to edit spatialit geometries?It would be easy to use related abstracts to add wfs support

**Comment by brentfraser** [comment]
Not ideal, but you could send the Spatialite database to your server and convert to shapefiles there.  Or use a browser based WFS-T solution?

**Comment by am2222** [comment]
@brentfraser  you mean I load a webpage in webview? I rather not to do that. I think If I can handel feature edit in GUI I can send related UPDATE,POST,GET requests to wfs server, but have no idea how to handle geometry editing

**Comment by brentfraser** [comment]
I haven't looked at the code for editing, but you could start by having a look at https://github.com/geopaparazzi/geopaparazzi/blob/master/geopaparazzilibrary/src/main/java/eu/geopaparazzi/library/features/Feature.java

**Comment by am2222** [comment]
@brentfraser  thanks very much

**Comment by moovida** [comment]
The editing tools are in the package ```eu/geopaparazzi/core/maptools/tools/``` of the geopaparazzi_core module.

**Comment by am2222** [comment]
@moovida  thanks very much I'' take a look at it I hope I can implement wfs
