### ISSUE TITLE
unable to access SD card in Android 6+

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#440]
When using Geopaparazzi's file browser (for setting the basemap, setting the custom sdcard path, etc) it is not possible to browse to the SD card.  This works fine on Android 5, but not on 6 or 7 (and likely newer too).

It may be necessary to check for permissions (https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android)

**Comment by moovida** [comment]
Possibly connected to #412 

Filesystem access of external cards got quite messy with version 6. I nopw have a phone with sdcard and will have a look at this in Bonn, but I can't assure anything. This might be quite challanging to solve.

**Comment by brentfraser** [comment]
I spent a day configuring and testing the Android Studio emulator with virtual devices having Android 5, 6 and 7.  Geopaparazzi's SD card browsing works fine in Android 5, but not in 6 and 7.  I tried both the basemap setting and the custom sd card setting.

Based on some Googling, after Android 5 the app must ask for permissions at runtime.  It looks like the most of the code exists in Geopaparazzilibrary's permissions system, but it may need a slight update and some debugging:  https://github.com/geopaparazzi/geopaparazzi/blob/77094e410811eeaeb9ca35bdd0e37cce5d72bf3d/geopaparazzilibrary/src/main/java/eu/geopaparazzi/library/permissions/PermissionWriteStorage.java#L53

**Comment by moovida** [comment]
For simplicity I ask for all the permissions at install. So if you uninstall geropaparazzi and then install it again, it should ask you for the write permission. Do you get an error when doing this? 
Because if not, I am afraid that there might be a bug I introduced that would block the browser fro getting higher than the internal sdcard root.

But then you are saying that on android 5 it works? I am a bit confused. Thanks a lot for this investigations, it will help a lot when going to work on it.

**Comment by brentfraser** [comment]
Some info on run time permissions: https://developer.android.com/training/permissions/requesting.html

Android 5 allows browsing with Geopaparazzi:

![sdcard_android5](https://user-images.githubusercontent.com/1638313/36318444-1c46e702-12fd-11e8-90e2-bf7414bc28e1.png)

so that's good.  But it might be easy for a user to get lost if they go up one more to the "root" of the device:

![root_android5](https://user-images.githubusercontent.com/1638313/36318721-f45b52f4-12fd-11e8-94ea-e79557650ad7.png)

We may need to do some work on the file chooser, or use a library:
https://android-arsenal.com/tag/35

**Comment by moovida** [comment]
The writing on external sdcard is not a permission problem. It is way more complex and to solve it it is necessary to somehow reqork the API to use FileProviders. This is something I do not need and find less important than other issues.

That said:

1. spatialite databases are now opened in readonly mode on readonly paths:

4f6d952 make spatialite db readable also if no style is defined - in readonly mode
5eb6502 review of external storage points + addition of multiple storage from resourcesmanager

2.There seems is a workaround for making datasets writable on external sdcards. I documented it here, please test it:

http://geopaparazzi.github.io/geopaparazzi/#_a_word_about_external_storages

**Comment by mj10777** [comment]
Just as a matter of interest, what happens when a .mbtiles file is being created?

**Comment by moovida** [comment]
That is indeed a good point. I assume you are talking about those that are generated autimatically from the mapurl configuration files, right?
The person writing the mapurl file will need to make sure that the mbtiles path is inside the 

```
/storage/YOUR-SDCARD/Android/data/eu.hydrologis.geopaparazzi/files
```

folder, if it is on an external microsd card.

**Comment by mj10777** [comment]
Yes. 
Should be added to '9.2.1. Mapurls: Custom tiles based maps'

**Comment by moovida** [comment]
You are right, added.
