### ISSUE TITLE
Profiles: Add ability to specify which layers are visible by default.

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#453]
Profiles currently have the ability to specify which Spatialite databases are attached to the map view, but no layers are visible by default.  It would be nice to be able to specify layers on with the profile is activated.  something like:

        "spatialitedbs": [
            {"path": "/Trails/rigstreet_v1.sqlite",
             "visible": "sites_campgrounds, sites_trails"}
        ]

**Comment by moovida** [comment]
done by @brentfraser
