### ISSUE TITLE
Expand Feature's linked Resource display to include PDFs.

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#454]
Currently (v5.5.5) is it possible to view images stored in a Spatialite database when they are related to (geospatial) features.  It would be useful to also view PDF files.

Also, allow users to see the linked Resource images and PDFs when doing a select-for-view, instead of just the current select-for edit.

Other future enhancements could include:
	- linking external files 
	- allow other file types (video, arbitrary types

**Comment by moovida** [comment]
Guess this can be closed now. You and Cesar did this.
