### ISSUE TITLE
Pictures stay in the project after deleting the note they are taken in

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#468]
I recognized that in one of my projects using the note forms with the possibility to take pictures, the corresponding pictures stay in the project after I delete the note. In one project I have still have over 200 pictures in the project even after all notes have been deleted. I can access the pictures in the device gallery and they  can be downloaded by using the export function of geopaparazzi.
Is that on purpose ?

**Comment by moovida** [comment]
Hmm, this looks like a bug. It is possible that in complex notes on deletion something goes wrong in the cascade deletion of the images connected.

**Comment by moovida** [comment]
fixed in 5698a30
