### ISSUE TITLE
Tanto mapurl doesn't work

### ISSUE THREAD

**Issue by ludovico85** [geopaparazzi/geopaparazzi#476]
Hi,
the mapurl service is not longer working with the last update. I get the following error when requesting a service:
ERROR: Failed the http GET request.

I use geopaparazzi 5.5.5 version

Thank you,
Ludovico

**Comment by moovida** [comment]
Hi @ludovico85 , I am discussing with the authors of the service and it seems that it is not maintained anymore. So most probably the functionality will be removed from geopaparazzi also. 
I hope I will at lesast be able to get the mapurl files to load somewhere to be manually installed.

**Comment by moovida** [comment]
Reference issue will be #478

Sorry to say it, but the tools will be gone. Closing this issue here.
