### ISSUE TITLE
which classes are used to render spatilite data to mapsforge

### ISSUE THREAD

**Issue by am2222** [geopaparazzi/geopaparazzi#477]
Hi,
Can you please give me some clues about structure of rendering spatilite data into mapsfourge? do you use mapoverlays or you have used tile data provider?

**Comment by mj10777** [comment]
The geoemtries are rendered with the **JTS Topology Suite, Vivid Solutions** found in 
geopaparazzispatialitelibrary/src/com/vividsolutions/jts

**Comment by brentfraser** [comment]
The Geopaparazzi project (I am not a main contributor) does not include any functionality to convert Spatialite databases to Mapsforge databases.  Geopaparazzi can use Mapsforge files as basemaps, and Spatialite databases as overlays.  I download Mapsforge files from Mapsforge and OpenAndroMaps sites.

**Comment by am2222** [comment]
@mj10777 so how you have shown them on mapsfourge mapview?

**Comment by am2222** [comment]
@brentfraser  so spatilite databases are rendered into as overlays? does it effects performance?

**Comment by brentfraser** [comment]
The files i have used are small, so performance is ok.

**Comment by mj10777** [comment]
It has been quite some time since I have worked on this ...

The Spatialite geometries are read 'AsBinary' and sent to the 'JTS Topology Suite' geometry and then rendered, I believe somewhere as a overlay in the central geopaparazzi painting.

**Comment by am2222** [comment]
@mj10777 thanks very much. I think it would be great if we use something like mapsfourge tile sources to paint them on mapview using mapsfourge mvt, as if we use overlays (as is used in geopaparazzi) ita performance will decrease

**Comment by brentfraser** [comment]
I guess the question is "Are we interested in using vector tiles to increase performance?".  Maybe, but it is not an issue for me (us?) currently.

**Comment by mj10777** [comment]
**JTS Topology Suite, Vivid Solutions**
* is a collection of classes, not a format
* it reads the result of ST_AsBinary(geomtry) as input

Look at:
GeopaparazziOverlay.java
* drawFromSpatialite

Retrieved a geometry:
import com.vividsolutions.jts.android.PointTransformation;
import com.vividsolutions.jts.android.ShapeWriter;
import com.vividsolutions.jts.android.geom.DrawableShape;
import com.vividsolutions.jts.android.geom.PathShape;
import com.vividsolutions.jts.geom.Coordinate;
import com.vividsolutions.jts.geom.Envelope;
import com.vividsolutions.jts.geom.Geometry;

    private WKBReader wkbReader = new WKBReader();
    // geomgeomBytes is the result of  ST_AsBinary(geomtry)
    byte[] geomBytes = stmt.column_bytes(0);
    Geometry geometry = wkbReader.read(geomBytes);

   PointTransformation pointTransformer = new MapsforgePointTransformation(projection, rawPosition,
                                drawZoomLevel);
   ShapeWriter shapeWriter; // Will paint the geometry
   shapeWriter = new ShapeWriter(pointTransformer);

calls drawGeometry()
        drawGeometry(geom, canvas, shapeWriter, fill, stroke);

        DrawableShape shape = shape_writer.toShape(geom);

                if (fill != null)
                    shape.fill(canvas, fill);
                if (stroke != null)
                    shape.draw(canvas, stroke);

**Comment by moovida** [comment]
Hi @am2222 , the method used to draw spatialite vector data is here:
https://github.com/geopaparazzi/geopaparazzi/blob/master/geopaparazzi_core/src/main/java/eu/geopaparazzi/core/mapview/overlays/GeopaparazziOverlay.java#L612

That said, a few comments:
* performance is not excellent, but has been working for us quite well
* the spatialite API is bad. It is hard to read and you will most probably find lost in it. But if you only need to draw, then the above method is all you need
* as yoou can see, vector data use mapsforge overlays, but mind, it is a very old mapsforge version, not compatible with the current and therefore not with vmt

Regarding vector tiles, I would be extremely interested to support that, if you have any reference to a library that can render vector tiles for android (also non android). I made very few research about it, but I think only teh mapbox sdk does, right? And I would not pull in that dependency just for vector tiles. If you have any idea/hint, you are welcome to open an issue to discuss it.

**Comment by am2222** [comment]
@moovida , @mj10777  thanks very much for your detailed answers. In fact I could implement reading from spatilite and converting into vectorlayer using vtm version of mapsforge. but performance is not so good as my geometries are about 40000, so I want to try  to query data based on extent as it does in mapniks input plugins and I think it will have some effects. About possible vector tiles I think mapsforge currently decodes them here :https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mvt/TileDecoder.java

I have not looked much and maybe I am wrong

**Comment by moovida** [comment]
Guess this can be closed here.
