### ISSUE TITLE
Profile: adding/removing project to profile does not work

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#485]
Create a new profile, add  basemap, overlay, and then a project file.  While the project file is shown properly in the Profile cardview, it is not shown on the Main View's Project Info view (the previous project is shown).

Removing the project form the Profile seems to work but it, but leaves behind some text on the card view:
Name
    0
Path
    /storage/emulated

Viewing the project info caused Geopaparazzi to crash: unknown error (code  14) Could not open database.

**Comment by moovida** [comment]
Fixed in 5ad3e86
