### ISSUE TITLE
Database corruption, STAGE cannot convert the gpap database and bombs out.

### ISSUE THREAD

**Issue by Hornbydd** [geopaparazzi/geopaparazzi#489]
So I've been heavily promoting geopaparazzi at a remote sensing workshop in Madagascar as a way of collecting field validation data for land classification. I took out with me two Sony Experia Z4 tablets. I had created a simple form that collected a variety of data and optionally some photos.

I demonstrated this and even got some of the delegate to install it on the Android phones. So far everything was good.

When I came to export the data they had collected this was when the disaster happened.

- On tablet I exit geopaparazzi application.
- Connect tablet to PC, set to USB transfer and copy the gpap database to my computer.
- I run STAGE using the 4 converter and it fails with the following error:

> ERROR
> ---------------------------------------------
> [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)

- Nothing I did fixed this and with great disappointment I had to say to the workshop delegates that 2 days of data collection was lost, not good!
- A colleague back in the UK was able to hack the database and recover 1 days worth of data and interestingly this corruption did not seem to occur on the mobile phones.
- I have spent the last couple of days investigating what could be the problem. We have identified that exiting the application does not commit recent changes to the database leaving it in a corrupt state. I know this as using a file manager on the tablet we can see that adding photos did not change the file size. We found that swiping the app to close it in the task switcher causes the commit to happen (but I have observed that this does not always happen) but a restart of the tablet definite commits. Only then when I copy the database to the computer to export using STAGE does it all work.

I would strongly suggest that this is a priority fix, to ensure a proper closer from the application to ensure the database is in a valid state and ready for export using stage.

I am aware that one can export on the device to KMZ but this is a less helpful format than shapefiles with media subfolders.

**Comment by moovida** [comment]
Hi @Hornbydd , I am sorry for the loss of your work. But honestly in all these years of work we never had database corruptions because of geopaparazzi.

Instead we saw many database corruptions due to moving the data from the device to the pc by USB cable. This method has been proving itself not safe. At the workshops we give we recomend to use applications like Airdroid or the like to make a clean fiel transfer.
That also explains why the data on the phone is not corrupted.

So I do not think this is something that needs a fix and I will mark this as invalid. If you think that is not the case, we can discuss it.

**Comment by Hornbydd** [comment]
I can confirm on the Sony Z4 tablet that if I exit normally, swipe to close then restart the tablet I can always copy or directly access the gpap file via USB and export using STAGE. However if I do not reset or swipe the app in the task switcher to close then when I copy by USB, STAGE often says it is corrupt and does not export.

Without even plugging it into a computer with USB we can see the time stamp and file size of the gpap file does not change following edits if the app is not swiped closed in the task manager. Because of this I do not think it is to do with the transfer to a PC via a USB cable.

**Comment by moovida** [comment]
Would you mind trying to copy the file over through airdroid? ( https://play.google.com/store/apps/details?id=com.sand.airdroid&hl=en )

Maybe we are then able to narrow down the problem.

The database operations are all done in realtime and the database is closed when the app is exited, so I am not sure what the problem could be. Maybe the fact that Android doesn't really close the apps.

Anyways it doesn't explain why with airdroid of other methods it never corrupts a file. We had the problems you are describing with USB transfers.

**Comment by Hornbydd** [comment]
OK I will give airdroid a go, I've never used this so need a little time to explore how to use it. I wonder if that software causes the commit to database to "flush" before it transfers the file and this is why you never experience anything bad?

We also wondered too that Android does not really close the app might be the root of the problem.

**Comment by moovida** [comment]
Thanks. 
I do not think it is airdroid triggering the data flush.

When I use the gvsig plugins [0] (which do a simple http transfer of the file), I also do not get any problem. 



[0] http://www.hortonmachine.org/hydrologis4gvsig_quickstart/hydrologis4gvsig_quickstart.html#_the_geopaparazzi_project_browser_and_simple_connection_server

**Comment by brentfraser** [comment]
Perhaps a buffer flushing problem?

**Comment by Hornbydd** [comment]
OK so I have been testing airdroid as a mechanism for transferring the gpap file from my Sony Z4 tablet to my PC before I convert it to shapefiles using STAGE.

So far so good. I have deliberately not swiped the application close and after the transfer to PC the gpap converts without error using STAGE. I have then gone back to tablet added a few simple notes/photo points, deleted some data and added a few more form data. Transfer by airdroid and it all seems to work.

I would suggest you explicitly state this on your excellent [manual](https://geopaparazzi.github.io/geopaparazzi/) as the recommended way of transferring data. A quick review of the manual and I see no discussion on best practise. If that had been there I would not have had the disaster in Madagascar...

Thanks for your quick responses.

**Comment by moovida** [comment]
Good to know it worked. 

Please always remember that we are all doing mostly voluntary work here. And geopaparazzi has been growing quite a lot over the years. Some pieces are missing from the manual and some pieces are found in the presentations of the workshops we share. Any contribution is welcome. Also just signalling the problem as you did. It is clear that if we do not see the problem, we give other problems priotiry.

Anyways here the issue for the manual update: https://github.com/geopaparazzi/usermanual/issues/8

**Comment by mj10777** [comment]
The comment from @brentfraser should also be added as the reason given.
 `Perhaps` a buffer flushing problem?

Something in the form of:

To avoid USB flushing problems (i.e. disconnection before all the data has been transferred) ....

**Comment by Hornbydd** [comment]
I think geopaparazzi is an amazing bit of software, very feature rich and giving ArcGIS collector a run for its money! I was also particularly impressed with the manual. As a developer (mainly in ArcMap) I know that half the battle is creating a robust piece of software the other half is providing a comprehensive manual. Software without a manual is pretty useless in my opinion so geopaparazzi with it's manual is a very polished product.

Also feedback is very important, it is impossible to trap all weird scenarios, so I try to feedback ideas/bugs where I can. So it is unlikely you have heard the last from me... :)

**Comment by brentfraser** [comment]
@Hornbydd Could you try using the Exit option on Geopaparazzi's main menu and see if the database corruption still occurs?

**Comment by Hornbydd** [comment]
@brentfraser I always use the Exit application from the menu to exit the application. I've assumed that closes the link to the gpap database and flushes any writes, but it does not seem to do that. Only when I swipe it shut on the task switcher and reboot the tablet do I see the gpap file size jump in size after edits. I must emphasise that this on the Sony z4 tablets, I don't get of these problems on the mobile phones.

**Comment by mj10777** [comment]
To close a Database (in Geopaparazzi, as in other Database drivers( the close method must be used
* this should always flush any data not yet saved by sqlite

As far as I remember this is also done in the deconstructor of the main class that opens the connection (in case it wasn't closed beforehand).

If this is still the case, there is nothing (programmaticly) more that can be done.

If it works correctly on one machine, then it should work on all
* if **not** then it is a problem of that machine and it's implementation of the underlining system.

**Comment by Hornbydd** [comment]
@tghoward I have but only because I'm not sure what it does and out of ignorance being copying both files.
