### ISSUE TITLE
Profile setting now forces same path

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#497]
In the new version 5.6.0 the cloud profiles feature has resulted in the fact that the location for the forms, basemaps, spatialite database, and project of the profile must be in the same path.
My solution however was based on separate paths for each, because I was using another app (drive sync) that synced data between the central google drive and each devices (samsung tablet). That does not work anymore.

**Comment by moovida** [comment]
Hi @GeoHigh125 , I am not sure I understand. 

If you create a a profile you can choose the various maps and stuff from different folders.

Can you describe a way to reproduce (understand) what you are saying?

**Comment by moovida** [comment]
Ohh, now I understand. I think this is due to the fact that the new profiles, that are full of new features and support cloud synching, are not backward compatible. Can you please try to recreate them from scratch?

I am sorry, this didn't jump to our eyes, it should at least have been mentioned in the release notes.

**Comment by brentfraser** [comment]
@moovida I don't think there is anything in the Cloud Profiles that requires all the components to be in the path?  All the paths given in the Profile are full paths.

**Comment by moovida** [comment]
@brentfraser , I agree completely, which is why I am confused. I think this is due to the missing backwardscompatibility with the old profiles format.

**Comment by GeoHigh125** [comment]
Hi @Andrea,

I have thrown away both profiles  and build up both again. Then it possible
to choose any folder. So problem is only that old profiles have to be
checked while updating. Issue can be closed.

Greetings,
Peter




Op di 15 mei 2018 15:34 schreef Andrea Antonello <notifications@github.com>:

**Comment by GeoHigh125** [comment]
Hi @moovida

Op di 15 mei 2018 16:57 schreef Peter Heerink <peterheerink@gmail.com>:
