### ISSUE TITLE
Move "Activate" to top on Profile properties screen

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#499]
[De]activating is the most popular  (only?) thing to do on the page so it belongs on the top.  Actually, it would be better if you could activate a profile on the card shown on the Profiles list screen.

**Comment by moovida** [comment]
I agree with you that the best thiing would be to activate profiles without entering them. I think a technical issue forced me to do the way it is now. I will look into it and see what can be done.

**Comment by moovida** [comment]
Solved in #500
