### ISSUE TITLE
Background maps not charged at restart

### ISSUE THREAD

**Issue by silviafranceschi** [geopaparazzi/geopaparazzi#501]
If I use as background map a .map file or an mbtile, if I close the application at restart it will not be loaded as background map using the default background (Mapnik).

**Comment by AndrewM-** [comment]
I can confirm that behaviour for 5.6.0 on Samsung phones and tablets.

**Comment by brentfraser** [comment]
A work-around for now might be to create a profile, attach a basemap, and activate the profile.

**Comment by moovida** [comment]
fixed in 7fb053a9
