### ISSUE TITLE
geopaparazzi crashes when user selects a form then tries to go back to the forms menu with the back button

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#504]
I have been giving geopaparazzi a big workout and have a few issues to report.  
A crash occurs on Android 4.4 and on Android 7, both Samsung devices with 5.6.0, when the user opens a data entry form, then tries to go back to the forms menu without entering any info into the data entry form.  You should receive a crash dump via gmail with my name on it with the stack trace.

**Comment by moovida** [comment]
related to #502

**Comment by brentfraser** [comment]
I can't seem to reproduce this bug on Android 5.1.1.   Could you give details on the steps?

**Comment by moovida** [comment]
Fixed in f8e8618d
