### ISSUE TITLE
Sometimes cannot switch from adding notes at map center  adding notes at gps position

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#506]
In 5.6.0. I sometimes can't switch location of form entries to being associated with the GPS position rather than map center.  I was testing with a Galaxy pad 3 and had started a new gpap file to ensure previous entries/issues were not affecting the current test.  I was in a vehicle but had enough signal for geopaparazzi to locate our position on the map.  I have seen this issue more than once but have not fully pinned it down yet.  Obviously this is a really big issue as loss of positions degrades my data.  Could you please make GPS position the default and have a warning displayed if no GPS position is assigned.  Will test further at my end.

**Comment by moovida** [comment]
The switch is turned off and goes into center map signal if there is no GPS signal. Also in that case it is not editable.
That said you are telling me that the switch was not enabled but geopaparazzi did have a valid signal? That would be a bug. And one I didn't notice even once in a long long time that this works in that way.

If that is so, we will need a way to reproduce it in order to be abel to fix it. Please let us know.

**Comment by moovida** [comment]
In case reopen it.

**Comment by AndrewM-** [comment]
I retested this issue in the field where I was out in the open.  It is usually possible to move the slider to GPS but if you then try and move it back to Map Center, it will not go.  I was recording a track at the same time and there were no issues with the track or any data recorded.  I wondered if this feature also required the map to *not* be centred on the GPS position.  Having tried all combinations, I think that there is an issue.  Perhaps if the switch cannot be moved, some reason can be provided.  As I am teaching at the same time as I am testing, I will have try and provide a test script that shows the issue later.

**Comment by AndrewM-** [comment]
For the record, I struck the issue again and had good GPS signal.  Does the switch get set only once when the application opens or is it retested each time the form with the switch gets the focus?  Version 5.6.1
