### ISSUE TITLE
Icons in map are not colorblind friendly

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#507]
Orange indicates that gps is available and red indicates that gps is not available.  However I find that the orange and  pastel pink-red are too close together and would like to have the no-gps symbol changed to be more attention demanding.  We are in a tropical environment with some of the strongest sunlight on earth, which may make the red symbols look pink.  I have attached a mockup of a suggested change, either a black X or ? mark would do, or something else that grabs attention.

![2018-06-05_nogps_mapicon](https://user-images.githubusercontent.com/5060805/40948009-21b3483c-68a9-11e8-86c1-c7cd9fd1fef3.png)

I also wonder if colourblind people can easily see the different shades used in geopaparazzi.  With twenty users, we should have two colourblind people in our crew, if the general rate for this condition applies.  If I print the image above as a grey scale image, the dark green and dark red are identical and the orange and light green are identical.

**Comment by brentfraser** [comment]
As a work-around, you could experiment with the Android setting: accessibility -> color correction.  The idea of using a different symbol is a good one.

**Comment by AndrewM-** [comment]
Thanks, I am a windows user and not an Android guru so it helps a lot to find out what I can do with Android settings to help the geopaparazzi experience.

**Comment by moovida** [comment]
Does this work for you @AndrewM- ? It would be indeed a colossal effort to review and change the icon-set and make it somehow interchangable. Doing it at an android level as Brent suggests would be the most robust way to go.
