### ISSUE TITLE
Hitting the custom SQL query button without having a SQL statement causes a crash

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#508]
More idiot proofing.  It would be good to validate the SQL statement before executing to avoid crashes.  If a stupid statement is put in, the database will not return anything, so I thing this is just a case of checking if SQL = nothing.

**Comment by moovida** [comment]
yes, that view needs some love. It used to be hidden as a help tool for power users. Now that it is accessible, some checks will be necessary.

**Comment by moovida** [comment]
doen in aeaa481b
