### ISSUE TITLE
Saving fails if form fields are empty

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#509]
If empty form fields are present when a user attempts to save, the failed validation dialog is shown.  This issue is my main issue so I will explore it in detail.

If in the form json code, mandatory = "no" is entered, the form will fail or crash (can't remember).  I have fixed my code to avoid mandatory = "no", but the presence of mandatory = "no" should be harmless.

If fields are empty I can't save form data.  As I collect ecological data, it is common for fields to be empty.  For example a bird nest may be empty so the fields for documenting eggs and nestlings will not be filled.  For fast moving subjects, I might want to take a photo and not record the species, as I can get that from the photo later.  I have been putting a question mark in as a default value as the presence of default values allows geopaparazzi to save form data.  That is a bit like putting "null" in empty fields as QGIS does.  I am not sure if this causes issues.  I notice that "-" is used elsewhere in geopaparazzi to flag empty fields.

**Comment by moovida** [comment]
The issue with empty form data should have been fixed. At least I thought so. @tghoward gave me a tags.json that I checked to solve the issue. Tim, could you check if your issue was solved?
@AndrewM- , could you supply my with a tags.json and a workflow to make the crash happen?

**Comment by tghoward** [comment]
I certainly save forms with empty fields all the time and it works fine. I'm not sure what the issue is here. Perhaps you have them all as mandatory="no", which I don't use? I agree that tag should be harmless, but perhaps you should try a form without it, @AndrewM- 

I have not yet checked to see if my issue was solved, but that involved forms with real errors that still got through the json validator.

**Comment by AndrewM-** [comment]
I have removed the mandatory="no" from all generated code before uploading to my device, so it was not a factor in the results of the field test.  Please find the test tags.json that I have been using.  I am also using JSHint in Notepad++ to check for syntax errors in my generated tags.json files.

[tags.zip](https://github.com/geopaparazzi/geopaparazzi/files/2078388/tags.zip)

**Comment by AndrewM-** [comment]
I have changed my forms generator to add a `"value" : " " ` default entry for all form controls.  With this line in the json file for each form field, I am not getting any crashes.

**Comment by moovida** [comment]
I think this was a different problem that has been solved in #504
