### ISSUE TITLE
Different map symbols for different forms

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#512]
Currently (5.6.0) there seems to be one map symbol for all types of form data.  Would it be possible to assign different map symbols to different types of data.

**Comment by moovida** [comment]
This is long on a wish-todo-list. being able to assign a style to the notes. We already have the database ready for this (there is a column named style). But the rendering system makes it difficult to handle, so this is delayed to when the rendering system will be changed.

Closing this until then.
