### ISSUE TITLE
Need a label field for form data

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#513]
On my map, I just see the word "wildlife" for wildlife observations.  It would be much better if I could nominate a field to display as a label.  Then I would see "swan", "heron", etc.  which is much more informative.  From a quality assurance perspective, our major issue is being able to ensure that the data we think we are recording is actually being recorded.  This is the major reason for not using commercial cloud-based services (as least the ones we have tried).  

Could the label also be displayed in the notes list, which is accessed from the map view?  I currently can't get much value from this screen.

**Comment by tghoward** [comment]
You can set a field to display as the label on the map using the "islabel" tag. See the second example at: 

http://geopaparazzi.github.io/geopaparazzi/#_numbers

Is that what you were looking for?

**Comment by moovida** [comment]
As @tghoward pointed out, that is the way to go.
