### ISSUE TITLE
Can we turn layers on and off, rather than form entries

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#514]
It would be good to be able hide all 'wildlife' records off at once.  Currently (5.6.0) it seems that I can only change the visibility of one item at a time.

**Comment by moovida** [comment]
This is not as simple as it sounds. but it will be something to definitely consider in the new rendering system, where I plan to have layers that can be overlayed and turned on and off.

For now this will be closed.
