### ISSUE TITLE
Need visual feedback on method of form note coordinate capture

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#517]
Although there is a switch for using map center or gps position as a coordinate source in the form menu, it is easy to forget which mode gpap is in.  There is also the possibility that someone sets gpap into map centre mode and does not realize.  One case where this can happen is when a user starts the gpap inside a shed or a vehicle where the device can't get a GPS position.  If they then collect data, it will not be located properly.   I am worried enough by this to mandate that users carry a Garmin GPS to record a track log as a backup.  With a continuous tracklog from the Garmin, I can match timestamps and recover positions.  

I would like to have a confirmation banner on the first save using map centre coordinates (reset when a GPS based-coordinate is captured).  Perhaps the color used for the form controls and text could also be different for map-based and gps-based coordinate capture.

Can I also ask if the coordinates are captured when the form is opened or when the form data is saved?

**Comment by brentfraser** [comment]
I think text on the Note's Action Bar (or maybe the Title Bar) would be better

![note_gps](https://user-images.githubusercontent.com/1638313/41297623-c35335ee-6e1c-11e8-89a9-7ae6d6ae8dcc.png)

**Comment by tghoward** [comment]
Another option is to make the user explicitly choose which method they will use. This would allow for other collection methods to be added over time. Such as using cell tower triangulation or position averaging (like I have in this screen shot). The setup here is the user taps the button to take a point, this menu of options comes up. If there is no GPS signal the GPS option will be disabled and they will get a toast saying there is no signal, you must use another method. 

![image](https://user-images.githubusercontent.com/6129193/41300862-c2ef390a-6e34-11e8-8ce8-c71683446760.png)

**Comment by brentfraser** [comment]
With respect to Notes, there is a switch
![notes_gps](https://user-images.githubusercontent.com/1638313/41315642-54aedc98-6e4d-11e8-9dcb-c722bb3cfa65.png)
But I think @AndrewM- was looking for more confirmation, during Note taking time, where the position information was coming from a that instant.   I suspect that when the GPS position becomes unavailable the switch will automatically slide over to "map center", but I haven't tried it.

I like your idea of more control over selecting the position method.  And maybe we could add some kind of accuracy measure to help the use decide?

**Comment by AndrewM-** [comment]
Much appreciated.  Perhaps in the notes list we could also indicate how a point was collected.  That way if we had an issue and points were collected using the wrong method, we could see how many points are affected.  Most of the issues I have raised have been about improving the ability to confirm that data has been captured properly after some data has been collected and before data collecting proceeds further.  If we can do this then we might still loose an hours worth of data but we should never loose a whole days worth.

Real world use case.  We do crocodile surveys so want to be able to use map centre-based data collection to mark the position of large animals that are in the river.  However we also want to record observations of riverbank vegetation at GPS-located positions.  As we are switching between the two methods, there is a significant chance that the switch is left in the wrong position.

**Comment by tghoward** [comment]
>  As we are switching between the two methods, there is a significant chance that the switch is left in the wrong position.

I think that would be solved by forcing the user to choose which method to use each time a note is collected, rather than have a switch the user must remember to apply.

**Comment by brentfraser** [comment]
Maybe make it a form variable to require the user to select the location method?

**Comment by AndrewM-** [comment]
Maybe the buttons in the form notes menu could change color depending on which geolocation method was selected.  This would avoid having to select the method each time but would be eye catching enough to help avoid errors.

**Comment by brentfraser** [comment]
I've been considering what you've said about the difficulty making out colors in bright sunlight.  So perhaps we should stick with text or big icons to indicate status.

**Comment by moovida** [comment]
This has been solved right now by adding to the title bar the method.
Actually I also adde the form name, ex.

examples (Map Center)
image note (GPS)

I prefer that over having to ask every time even if you are using it always the same way. If one day we should have GPS averaging, we will sure have to talk abotu it again.

**Comment by AndrewM-** [comment]
Please note that the logic of this feature is not correct yet.

1. If I use Gpap without looking at the map and just go directly to the data form, the switch suggests that map centre is being used.  In this case the GPS should be used.
2. Does the switch have to be orange to be active?
3. The switch is very sticky.  If I do manage to move it across, it is almost impossible to move it back again.
4. The choice of map centre or GPS position should be a something that can be set before each form entry.

This item is currently at the top of my wish list.
