### ISSUE TITLE
Ability to sort notes list by entry order or by timestamp.

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#519]
It would be nice to be able to check the most recent form notes.  To do this requires sorting of the lists from newest (top) to oldest (bottom).

**Comment by moovida** [comment]
Isn't that already the case? Normal sorting is by insertion and then we can choose sorting by name and distance

**Comment by AndrewM-** [comment]
I thought that this might be the case but it was not clear.  However, it can never be assumed that records appear in entry order when not sorted so a sort on the index or data stamp has to be applied.  I am having issues with QGIS not stepping through unsorted records in entry order so am keen for an explicit statement that the records are sorted by entry order when no other sort is specified.
