### ISSUE TITLE
Losing form data due to using back key once too many times

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#523]
With more complex forms losing data becomes more frequent.  Would it be possible to raise a confirmation dialog when the user moves back once to many times and is about to loose unsaved data?

**Comment by AndrewM-** [comment]
This may be an Android version issue.  With Android 7, I can touch the form title bar to close a multicombo.  With Android 4.4, I have to use the back button.  The only control that is a bit tricky with gpap in Android 7 is the integer control (on Samsung S7).  If you use the next button on the keypad after entering a number, it jumps to the next integer field and not the next field.  I do like the done key and wish that all keyboards and keypads had one, as it is a good way of finalising entry of data in a field.

**Comment by moovida** [comment]
Solved in #510
