### ISSUE TITLE
Export files are stored in the root of the virtual SD card

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#524]
Hello, 

Would it be possible that generated exportfiles of the gpap like the gpx , kmz and PDF's are generally stored in the same folder as the gpap is in ( the project folder)
I used an extra sync tool that can sync any new generated file to a dedicated google drive folder.
In the former version the generated PDF file was stored in this project folder.
With the Sync tool I could copy / sync the generated PDF file without any extra work to the company report folder to a  Google Drive.
Now the generated export PDF file is stored in the root of the  virtual SD card, the Sync tool, however the tool can only sync a complete folder, resulting  in copying all files and subfolders of the virtual SD card. 

Thx
Peter

**Comment by moovida** [comment]
Exports now follow all the same pattern:

* they are exported in the geopaparazzi/export folder
* their name is made if the project name _ type + timestamp of export
