### ISSUE TITLE
Save button in notes forms

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#527]
As we use devices for recording data in small helicopters (imagine entering data whilst mustering cattle), I am trying to make all the controls as large as possible.  The one control that is used on every record and that is is very small is the save button. I wish I had the option of putting a save button in the body of the form as well as having the save button at the top.

**Comment by brentfraser** [comment]
Personally I think it should be a big button hard-coded at the top of the note.

**Comment by AndrewM-** [comment]
That sounds good.

**Comment by moovida** [comment]
Please let's remember that it should be an Android app following some android design rules. Then it should be of good usability by default. I will never place a big button hard-coded on the top of the note :-)

That said, probably a FAB button should do. The save place is indeed wrong.

**Comment by moovida** [comment]
The thing is that usually the design rules are made for usability. I placed the icon on the toolbar, but in this case the FAB is sure better.

**Comment by moovida** [comment]
Done with FAB
