### ISSUE TITLE
Can the device details be automatically recorded in the project metadata

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#530]
I need a way to create a GUID for gpap data to make sure that I do not import the same data twice.  The way I have used previously is to combine the device serial number with the record timestamp.  The timestamp alone is almost a GUID but with many devices being used concurrently, some identical timestamps will be generated.  

The make and model device should also be included if possible as some devices may develop issues such as failing to record tracks (I have seen garmins with this issue) or cameras full dirt.  Having make and model would help me track down sick devices.

**Comment by moovida** [comment]
I have added the device id, if available (IMEI) to the default values of the metadata.

Done in 195a5a3b
