### ISSUE TITLE
Creating new gpap files when a profile is locked to a project file

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#531]
I could not find the menu option for creating a new file, when a user asked me.  I knew where it should be and it took me ten minutes to figure out that it was not being displayed due to a setting in the profiles.  Would it be possible to leave the new file command in the menu but display a message telling the user that the current profile disallows creation of new data files.  That would be less confusing to users.

**Comment by moovida** [comment]
After some discussing, we decided back then that if a project is supplied by the profile configuration, then the user should not be able to create new projects, but should use the supplied.

If no project is defined, one can create and switch.

**Comment by AndrewM-** [comment]
That is fine, but can we tell the user why they cannot create a new file.  E.g. 'Current profile does not allow new data files to be created".  There was no argument against your logic, just an observation that when the _new file_ option disappears, that can be very confusing and it can be hard to find out why.

**Comment by moovida** [comment]
Ok, agreed.

**Comment by moovida** [comment]
Done in 88adff73
