### ISSUE TITLE
Edit Vector tools are not avaiolable

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#532]
I have installed via  the import function the standard spatialite database and activated the database.
But if a start the editing tool I only get the selection icon and not the other vector functions. 

![image](https://user-images.githubusercontent.com/9881088/41818735-0a047c04-77b5-11e8-9e3c-1958286964cf.png)

**Comment by brentfraser** [comment]
I've made a start documenting Editing https://geopaparazzi.github.io/geopaparazzi/#_editing_features
- turn on the  layer for viewing
- long tap the edit button to show layer list
- select a layer for editing
- return to Map View

**Comment by GeoHigh125** [comment]
Mea Culpa,

I did not read properly the manual for this. It is working as it is described section 7.2
Issue can be closed
