### ISSUE TITLE
Main Menu - Create New Project and select tile source are not in action bar

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#535]
Hi,

If I use my device in the Portrait mode, there are two submenu's less in the main menu as that I use it in the landscape mode.
They are replaced by to new icons in the actionbar . This is however not very convenient for an user. 
It seems that there is enough room for both icons in the portrait mode.

However is it not possible to keep the two sub-menus in the main menu in both cases

**Comment by AndrewM-** [comment]
I think that I have previously raised both issues.

**Comment by GeoHigh125** [comment]
Has been solved / clarified in the new release 5.6,1
