### ISSUE TITLE
Multiple instances open or Geopaparazzi not quiting

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#548]
I am not an expert android user, but it looks like the current version 5.6.1 does not always quit after the exit menu has been selected.  Another way that the appearance of Geopaparazzi not quiting would occur if the user had launched more than one copy of Geopaparazzi, which should not be possible.  I have experienced this several times, where when I go to the stack of open applications, select Geopaparazzi, use the exit menu and find that Geopaparazzi is still in the list of open applications.  If I close all, Geopaparazzi goes away.

**Comment by GeoHigh125** [comment]
I checked this. I have the same experience geopaparazzi is still active ass application  after using the exit menu

**Comment by AndrewM-** [comment]
My new Samsung phone was having issues making calls.  The phone app was locking up and I was unable to end a call.  I also could not make calls.  I am not sure if this has anything to do with Geopararazzi, but I need test this.  I could not make a call, then I closed Geopaparazzi, then I could make a call.  Again the quiting bug was occurring.

**Comment by moovida** [comment]
This is quite strange. Though I have to say that it happened to me once. That time I thought that I had forgotten to get out properly. Usually geopap quits properly. 
Thinng is that nothing changed in the exiting code. It might be related to the new notification system. The one Android forces you to use from version 8 on, if you want to have precise background GPS.
This might mean that there is a race condition somewhere between exiting and stopping the service? Not sure, this will need to be investigated and won't be easy. If you have information, let it flow here.

@AndrewM- , phone calls should really not be blocked by geopap. The system would never allow such an interaction.

**Comment by AndrewM-** [comment]
@moovida I have not had the phone issue for couple of days.  It was an extreme problem as I could not hang up on an ongoing call, the screen was frozen.  Luckily I was just checking my voice mail.  So I thought I would report it just in case.  I was getting calls and reception, then I would suddenly have nothing and not be able to make outgoing calls on a new mobile.

**Comment by AndrewM-** [comment]
Close all applications on Android stops Geopaparazzi so I wonder if the exit command in the application menu has just stopped working.

**Comment by moovida** [comment]
I have tried to clean up a little more the exit. Please check if it works in the next release. Else reopen this please. It is really difficult to recreate this problem.
