### ISSUE TITLE
Adding Spatialite data to the mapsforge

### ISSUE THREAD

**Issue by alich65** [geopaparazzi/geopaparazzi#553]
I want to create a Hello World application using geopaparazzilibrary and display Spatialite data onto the mapsforge map but source code of geopaparazzi is very complex!
What is java code for do this?
Thanks in advance.

**Comment by moovida** [comment]
Hi @alich65 , I am afraid that would take too much work. We do not have a hello world application. Your best way is to start removing parts from the app itself. 

But from what you write I think that you are not looking for geopaparazzi. Have a look at the mapsforge project. For that library they did a lot of example apps and I think there is also a way to add spatialite data.

**Comment by alich65** [comment]
Thank you very much for your help
