### ISSUE TITLE
Notelist - Type to Filter

### ISSUE THREAD

**Issue by GeoHigh125** [geopaparazzi/geopaparazzi#556]
If you use the >Type to filter function< in the Notelist it filters perfectly.
But if you then have entered into one of the note using the menu and you come back, the Type -to-filter is still shown but is not active. It would be fine is to have the filter set again then automatically based on this
![notelist_type_1](https://user-images.githubusercontent.com/9881088/43707459-6f0f7a3e-9968-11e8-93c1-8b3615de2962.PNG)
![notelist_type_2](https://user-images.githubusercontent.com/9881088/43707463-72216f3e-9968-11e8-8370-15d74283ab40.PNG)

**Comment by moovida** [comment]
fixed in c92d5bcb
