### ISSUE TITLE
Don't want to confirm photo after taking it

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#557]
I would rather drop this step.  I photograph animals and things that move and would like to be able to take photo after photo. I can delete the bad ones later.  Perhaps the confirm step could be optional or a delete function be added for photos that have already been taken.
Maybe I should expand.  I typically take 400-700 photos per field trip.  My record is several thousand.  Each and every second spent logging something counts.

**Comment by moovida** [comment]
Hi @AndrewM- , I am afraid this is not possible for how geopap handles pictures now. 

We currently rely on the system's camera application. That one inserts the extra step. 

I found out that it is possible to start it in quickCapture mode through the intent parameter:
```
cameraIntent.putExtra("android.intent.extra.quickCapture",true);
```

but it doesn't work on my pixel XL, so I immagine that on non vanilla systems it will work even less.

If someone has an idea on how to handle this, I am willing to try it out.
