### ISSUE TITLE
OpenAndroMaps map not loading at all

### ISSUE THREAD

**Issue by MB1965** [geopaparazzi/geopaparazzi#562]
I am experiencing problems with the OpenAndroMaps GB maps. Both maps from 08/2018 and 09/2018 don't work anymore. 
http://download.openandromaps.org/mapsV4/europe/Great_Britain.zip

"Geopaparazzi 5.5.5 reported "The selected file is not supported as basemap.", while 5.6.1 showed no error when selecting it. But in both cases the mapview stays empty. Other applications like Cruiser and Oruxmaps don't seem to have any problems with this map.

I tried some other countries and they were working, e.g. Scotland.
http://download.openandromaps.org/mapsV4/europe/UK_Scotland.zip

**Comment by moovida** [comment]
Ok, I think I fixed this in 83f60a26

The fact is that we are still sitting on an ancient version of mapsforge that support only up to version 3 of the maps.

I made some fixes to be able to read also version 4 and it seems to work fairly well. Will be in next update.
