### ISSUE TITLE
Forms: onetomanystringcombo needs to set titles on select of new main combo item

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#564]
I'm trying to create more documentation on the tags.json file format.  I see that for onetomanystringcombo type of combo the "itemname" is used for the label on the form (good!) for the connected combos..  But the labels are rendered only when the form is shown, so if I select a different item from the main the labels are not changed.  In the screenshot below, the default is "items 2", but I then selected "items 1".  The labels should read:
subitem 1 of item 1
subitem 2 of item 1

![onetomanystringcombo](https://user-images.githubusercontent.com/1638313/46263873-716dd600-c4d2-11e8-91cc-8719f719bc04.png)

**Comment by moovida** [comment]
fixed in a5bba8b9
