### ISSUE TITLE
If geopap starts in an area with no mobile/cell service, does it prevent gaining service in areas where service is available

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#567]
I had a case where I went for a walk in the mountains and started Geopaparazzi in a valley with no cell service.  I was using Google Maps to find my way to the trail head so the phone did have service until I entered the valley.  When I climbed the mountain, I met other hikers who were getting calls and messages on my cell phone providers service but I had no service at all.  At the top of the mountain, I had a clear line of site to more than one town which should have towers.  I had no phone signal all day.  One the way home, I stopped in a town and was sure there was an issue with my phone, so I closed Geopaparazzi and restarted the phone and then I received a lot of messages.  Places that have good GPS signal and no cell service are not that common.  I am sure I have had one other similar incident and perhaps need to test this more.

**Comment by AndrewM-** [comment]
I have had another incident where after a cyclone/hurricane our cell coverage was interrupted.  My Samsung phone could not detect when the coverage came back.  I was not using Geopaparazzi.  I have made a bit of noise about this behavior as failing to call in can lead to search parties being sent out and more likely just getting an official warning at work for not complying with call-in procedures.  It is a hard issue to test properly as you need a clear view of the sky without cell coverage.  Currently, I think is just my phone and not Geopaparazzi and it was just coincidence that the loss of cell coverage when it was available occurred at the same time.

**Comment by brentfraser** [comment]
I think is it likely your phone.  I've tested Geopaparazzi on areas with no cell coverage and a clear view of the sky (Canadian Rocky Mountains).  My Samsung Galaxy S4 had no problem connecting wight the cell system when I came back into coverage.

**Comment by AndrewM-** [comment]
Hi Everyone, I think the issue is an Android issue that affects Samsung phones in particular.  I found this link.  https://www.technobezz.com/phone-says-no-signal-android-samsung/

**Comment by moovida** [comment]
Thanks for this followup @AndrewM- , this removes me a bit of anxiety :-)
I will close this issue for now.

**Comment by AndrewM-** [comment]
@moovida There was a follow up article that is worth looking at.  Again the behaviour is a Samsung/Android issue, rather that a Geopaparazzi issues.  The only work around, I have is to make the notification icons larger so that it is more noticeable if there is an issue. I have had the issue about 3 times in 3 months. Raising the issue caused me lots of anxiety by the way, so I am glad that it was not just my imagination and glad that it is a Samsung/Android issue.  A few days ago I was at my desk in the centre of a city and tried to ring my mobile from my desk phone.  It didn't work due to this issue.  That was the breakthrough that allowed me to confirm the issue and track it down.

https://www.technobezz.com/fix-samsung-galaxy-service/

The lines below are the ones from the article that caught my eye.  

> There are multiple reasons that may cause Android No Service issue. Sometimes it occurs because of the radio signal, the radio signal is turned off automatically due to some conflict with the WIFI and GPS which give rise to the mentioned issue.
