### ISSUE TITLE
Allow relative urls in cloud profile json

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#574]

**Comment by brentfraser** [comment]
Currently only  full URLs are allowed in the Cloud Profiles json for downloading (and uploading) files listed in the json.  This can cause added work for server admins moving profiles between servers: when the server address is changed, the content of the josn must be changed.

A solution would be to allow "relative" URLs which would be relative to the Cloud Profiles URL in the Settings.  So for example if the web address was missing from a URL in the json, Geopaparazzi would prepend the web address from the Cloud Profiles URL used to get the json.

The json URLs would be fixed up at profile download time to ensure they are full URLs when stored in Geopaparazzi.

Examples of allowed relative URLs would be:
```
"url": "//172.17.194.38:80/geotabloid_lite/data/demo/vienna/tags.json"
"url": "/geotabloid_lite/data/demo/vienna/orthofoto_vienna.mapurl",
"url":  "geotabloid_lite/data/demo/vienna/wfs_vienna_db_3857.sqlite",

```

**Comment by moovida** [comment]
merged
