### ISSUE TITLE
Forum for discussing isssues?

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#590]
Sometimes I can't tell whether an issue is a Geopap. issue, an Android issue or more likely, a user issue.  In these cases, it would be better to present the issue in a user forum, rather than heading straight to GitHub to raise an issue.  What do you think?

**Comment by moovida** [comment]
Yes, I completely agree on that. I usually find it better to start a discussion in the list, so more people can join and if verified, open an issue.

**Comment by AndrewM-** [comment]
List? I might be missing something.

**Comment by tghoward** [comment]
This list:

https://groups.google.com/forum/m/#!forum/geopaparazzi-users

There is also dev

https://groups.google.com/forum/m/#!forum/geopaparazzi-devel
