### ISSUE TITLE
Spatialite with PROJ 6 support

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#596]
I have just started orientating myself with the changes for Spatialite 5.0 with PROJ 6.

The major problem will be that PROJ will always need to know where certain external files are when running:

* proj.db
* any grids that may be needed

--- 
So for the moment, it would seem to me, that any application using a spatialite library (that has been compiled with PROJ 6)

* must know where to find them using the *environment variable* : **PROJ_LIB**

---
This would mean that **Geopaparazzi** would have to include a **proj.db** and any needed grids
* so the install program must contain these files and set **PROJ_LIB** based on where it was installed

---
This should be considered 'brilliant' idea  Number 1  on how to resolve this problem.

Thoughts?

**Comment by moovida** [comment]
Hi @mj10777 , great to hear from you. I didn't know about these implications of proj 6.

Does this mean that the spatialite databases will no longer be around 5 megabytes, because the definitions are all kept inside the proj.db?

What is the size of the proj.db?

Actually I see no big issue to copy the db into the geopaparazzi configurations folder and have it always living there. The problem I have is that I have no idea how to set an environmental variable in Android from an application or during its installation. Do you have any knowledge about that?

**Comment by mj10777** [comment]
>> Does this mean that the spatialite databases will no longer be around 5 megabytes, because the definitions are all kept inside the proj.db?

For the moment no.

>> What is the size of the proj.db?

5.2 MB

>> The problem I have is that I have no idea how to set an environmental variable in Android 

Don't you use **SPATIALITE_SECURITY=relaxed** somewhere when Shape-Files are imported?
* that would be the same process

>> during its installation

For this to work, the files must be installed in
* **/somewhere_over_the_rainbow/share/proj/**

**PROJ_LIB** must then be set with:

export PROJ_LIB=**/somewhere_over_the_rainbow**

PROJ would use that value and add **/share/proj/** to open:
* the proj.db or any grid files that may be needed

**Comment by moovida** [comment]
> > > The problem I have is that I have no idea how to set an environmental variable in Android
> 
> Don't you use **SPATIALITE_SECURITY=relaxed** somewhere when Shape-Files are imported?
>
> * that would be the same process

No, I am afraid we never enabled shp support. I think partially due to the environmental variables problem. I am still not sure this can be done from within an app.
 
> > > during its installation
> 
> For this to work, the files must be installed in
> 
> * **/somewhere_over_the_rainbow/share/proj/**
> 
> **PROJ_LIB** must then be set with:
> 
> export PROJ_LIB=**/somewhere_over_the_rainbow**
> 
> PROJ would use that value and add **/share/proj/** to open:
> 
> * the proj.db or any grid files that may be needed

I assume that would be straightforward then.

**Comment by mj10777** [comment]
I am correcting the Spatialite PROJ.6 wiki page and noticed that the setting of **PROJ_LIB** was incorrect.
* have adapted the above text
  * with the directory that contains **proj.db**

Spatialite PROJ.6 wiki page:
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=PROJ.6

----
A quick search turned this up:
https://stackoverflow.com/questions/7597058/android-setget-environmental-variables-in-java

>> Android API 21 provides a way to set the environment variables. To set an environment variable, invoke Os.setenv.
>> See this android.system.Os documentation and this setenv(3) documentation.
>> Each process has its own environment, which is copied from the parent process's environment. So the environment variables are per-process.

---
This is very important, so needs to be resolved.

Please try this out and inform me of the result.

**Comment by moovida** [comment]
> I am correcting the Spatialite PROJ.6 wiki page and noticed that the setting of **PROJ_LIB** was incorrect.

Ok, so just to have a final reference, we need to add a env-variable that points to the folder that contains the proj.db like:

```
 export PROJ_LIB=/somewhere_over_the_rainbow/share/proj
```

> A quick search turned this up:
> https://stackoverflow.com/questions/7597058/android-setget-environmental-variables-in-java
> 
> > > Android API 21 provides a way to set the environment variables. To set an environment variable, invoke Os.setenv.
> > > See this android.system.Os documentation and this setenv(3) documentation.
> > > Each process has its own environment, which is copied from the parent process's environment. So the environment variables are per-process.
> 
> This is very important, so needs to be resolved.

Ha, I did look a lot, but could not find the right set of keywords it seems. Thanks for the link. Os.setenv seems the answer. Even if I do not understand from the documentation if that sets envirnmental variables only for child processes? You might have better insight in the unix setenv function. Does this set an environmental variable that can also be used by the process setting it?

> Please try this out and inform me of the result.

Yes, I will let you know as soon as I test it.
Do you have builds available to share already?

**Comment by mj10777** [comment]
I used:
* android java environment variables

---
>> Do you have builds available to share already?

No, I have been 'offline' for a while and am just starting to work back in.

---
Linux (including Android) always have a 
* parent --> child relationship
  * the child will see what the parent (or grand-parent) has set

Assuming that **Geopaparazzi** is the parent
* sets **SPATIALITE_SECURITY** or **PROJ_LIB**
  * the child (Spatialite) and the grand-child (PROJ)
    * should see it, but **cannot** change it in a way that will effect its parent

i.e.: if the grand-child (PROJ) changes it
* the change will effect the grand-child (PROJ)
   * but the parent (Spatialite) or grand-parent (Geopaparazzi)
      * will retain the original (unchanged) value

If the grand-child (PROJ) set a environmental variable
* the parent (Spatialite) and grand-parent (Geopaparazzi)
  * will **not** see it

This is the main logic that prevents viruses from causing damage.

In **Windows** there is only one Environment
* any change effect everyone

---
If you plan to use **SPATIALITE_SECURITY**

* create a function to set to either
  * **relaxed** or set to empty

The calling function that needs **relaxed**
* should call the setting function when needed (any external file reading)
  * and when completed, call again to set it to empty

**Comment by moovida** [comment]
> Linux (including Android) always have a
> 
> * parent --> child relationship
>   
>   * the child will see what the parent (or grand-parent) has set
> 
> Assuming that **Geopaparazzi** is the parent
> 
> * sets **SPATIALITE_SECURITY** or **PROJ_LIB**
>   
>   * the child (Spatialite) and the grand-child (PROJ)
>     
>     * should see it, but **cannot** change it in a way that will effect its parent

That is what puzzles me. I was quite sure that spatialite would be a child only if a new process is spawned. If it lives inside the same virtual machine it will not be able to see the environmental variable.

Well, we will see. I will do a test when the time comes, so we will be sure.

**Comment by mj10777** [comment]
Do you have time for this today?

I completed a complie for Spatialite only and am now archiving the result.
* will upload this in a few minutes.

Also archives for the latest PROJ.6 grids and proj.db have been uploaded.

**Comment by moovida** [comment]
Ok, I will try my luck this afternoon, maybe already this morning.
Just send the link when they are up.
Thank you!

**Comment by mj10777** [comment]
The main page has partialy been updated:

https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_5.0.0.mk

----

Here a the needed 3 wget command shown on that page:

wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20190707.libjsqlite.5.0.0.tar.bz2

The following are the latest PROJ.6 grids and a **proj.db**.

All the files of these two archives should be extracted and placed in an extra directory inside the main Geopaparazzi directory
* **share.proj**

The **PROJ_LIB** should be set with:
* **geopaparazzi_directory/share.proj**


wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20180915.proj-datumgrid-1.8.zip

wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20190701.proj.db.tar.gz

**Comment by mj10777** [comment]
Further notes for testing:

Assuming that Geopararazzi stil transforms to WSG84 for a map display
* once the map is rendered should be a sign that it works

Sandro has introduced a a **spatialite_i/w/e** messages
* which for Android will call **android_log_print**

so any returned errors should be shown in a logbook.

```c
#define spatialite_d(...) __android_log_print(ANDROID_LOG_DEBUG, "Spatialite", __VA_ARGS__)
#define spatialite_i(...) __android_log_print(ANDROID_LOG_INFO, "Spatialite", __VA_ARGS__)
#define spatialite_e(...) __android_log_print(ANDROID_LOG_ERROR, "Spatialite", __VA_ARGS__)
```

**Comment by moovida** [comment]
Hi @mj10777 , good news from this side. The libs work perfectly and also setting the system variable. 
I did only few tests, but loading of spatialite layers works. 
I did a test at the begin without setting the environmental variable and it didn't work, so I am sure it is really using what it should.

Downside is that we are getting 10 mb more in the installation package. I assume the rasterlite part is not yet there right? You said "spatialite only", I assume you meant that?

Everything is committed in the vtmtest branch, which will soon be the next master.

**Comment by mj10777** [comment]
>> Downside is that we are getting 10 mb more

They always do ...

>> I did a test at the begin without setting the environmental variable and it didn't work

Did you look in the log and find the expected spatialite_e messages?

>> You said "spatialite only", I assume you meant that?

Yes, that will take a while since most of the depended packages have been updated.

>> setting the system variable

A small sample on how this is done would be useful, so that others using the library can see how it is done.

**Comment by moovida** [comment]
> Did you look in the log and find the expected spatialite_e messages?

No, didn't look that up yet.

> > > setting the system variable
> 
> A small sample on how this is done would be useful, so that others using the library can see how it is done.


Sure, the following is what I added. It pulls the proj.zip from the assets folder, unzips it into the app folder and then sets the environmental variable (last line).
```
            File projFolder = new File(applicationDir, "proj");
            File projFolderWithDate = new File(applicationDir, "proj20190708"); // to keep versions
            File projDbFile = new File(projFolderWithDate, "proj.db");
            if (!projDbFile.exists()) {
                File zipFile = new File(applicationDir, "proj.zip");
                AssetManager assetManager = activity.getAssets();
                InputStream inputStream = assetManager.open("proj.zip");
                FileUtilities.copyFile(inputStream, new FileOutputStream(zipFile));
                try {
                    CompressionUtilities.unzipFolder(zipFile.getAbsolutePath(), applicationDir.getAbsolutePath(), false);
                    projFolder.renameTo(projFolderWithDate);
                    GPLog.addLogEntry("Uncompressed and renamed to: " + projFolderWithDate.getAbsolutePath());
                } finally {
                    zipFile.delete();
                }

            }
            Os.setenv("PROJ_LIB", projFolderWithDate.getAbsolutePath(), true);
```

**Comment by moovida** [comment]
I will close this, since it is implemented.
