### ISSUE TITLE
Support zip format for Mapsforge maps

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#598]
Both Mapsforge and OpenAndroMaps have their .map files in zip containers for download. it is a big pain to have to download, unzip, then transfer the .map file to the phone.  If Geopaparazzi was able to read the map file from the zip container, it would make the data management much easier.

**Comment by moovida** [comment]
@brentfraser , I never saw mapsforge maps in zip containers. The official download of mapsforge has them in .map. Probably also because they do not compress any more than what they are.

It might be that openandromaps does it, because they ship also the rendering themes together with the map?

**Comment by brentfraser** [comment]
You are right, mapsforge downloads are .map files, so that's good.  OpenAndroMaps downloads are zip files with only one file in it (the .map file) which is very annoying.  Interesting thought about the theme file; I wonder if there is a way to set the theme file in software, instead of requiring they have the same name as the .map file?  That way the theme file would only have to be downloaded once.

**Comment by moovida** [comment]
It is indeed possible to set the rendertheme programmatically. There are a few problems with that though:
1) the renderthemes are dedicated to the theme and map file. So the xml could reference information not inside a particular map file. The andromaps have isolines information for example, which are not available in mapsforge maps (I am guessing a bit here)
2) I got several andromap files that in the zip also have a folder that contains the pngs that make the theme (ex polygon fills).
Not so easy...

**Comment by brentfraser** [comment]
Perhaps the zip contents vary by region (or version/date)?  All of my Canada zip just have a .map file.  

Anyway it would be difficult to have GP look into zip files to see if they contained .map files so it could list them on the file chooser.  So perhaps I'll just have to put up with inconvenience for now.

**Comment by moovida** [comment]
in the past I have dealt with that (maybe even for that map issue) and I solved it with some androidzip app. It allowed me to select it on the *save as* dialog and then would pass through that and unzip it in the destination folder. It is then very smooth, same as downloading a file, once you are used to it.
Unzipping programmatically would be indeed an effort, even if I think we have all the methods in CompressionUtilities... I will have to look. There should be an unzip to folder. 

But then we would need a download mapsforge map utility, which I eagerly wish to have for a long time :-)

**Comment by moovida** [comment]
closing this here
