### ISSUE TITLE
[vtm-renderer] Need to have a way of selecting tables when adding spatialite db via Profiles GUI

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#605]
The user can add spatialite layers using the Profile Settings, but currently there is no way to select the table within the database.

A possible alternative workflow would be to update the Profile from the Map View.  When the user exits the Mapview and if the layer list is different from the Profile layer list, ask if they want the Profile updated.

Or do both.

**Comment by moovida** [comment]
The layer manager handles selecting a table (as layer) from a spatialite database. If you select a spatialite file it will popup a simple multiselection dialog

**Comment by brentfraser** [comment]
I can add the Spatialite database in Profile Settings, but I don't get a list of tables.  This was OK in the old version as in the Map View I could then select the table.  Of course the user could just add the Spatialite database + table in the Map View, but currently there is no way to save the layer list back to the Profile.

**Comment by moovida** [comment]
Still not sure if I got the problem right. But if it is about selecting a table name from a spatialite db, you can use the same code used here:

https://github.com/geopaparazzi/geopaparazzi/blob/master/geopaparazzimap/src/eu/geopaparazzi/map/gui/MapLayerListFragment.java#L469-L538
