### ISSUE TITLE
crash when adding a WMS map to Profiles -> Basemap

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#606]
I have a URL to a WMS that has layers available in EPSG:4326, but the boundingbox is in a unrecognized SRS: EPSG:3978.   This causes Geopaparazzi to crash.
To test use https://geogratis.gc.ca/maps/CBMT?VERSION=1.1.1
This is due to a null crs string in ProfilesSettingsActivity.java, 239
`                    if (crs.equals("CRS:84") || crs.equals("EPSG:4326")) {`                    
It needs to be changed to 
`                    if (crs != null && (crs.equals("CRS:84") || crs.equals("EPSG:4326"))) {`

**Comment by moovida** [comment]
merged in fix, thanks
