### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by Mutembeibrian7648** [geopaparazzi/geopaparazzi#608]
Main menu on my app (version 5.6.5) does not include the option to ''Select Tile Source''

**Comment by moovida** [comment]
Can you show a screenshot o fthe actionbar and of the main menu?

**Comment by Mutembeibrian7648** [comment]
![Screenshot_20190806-144053](https://user-images.githubusercontent.com/53810157/62537810-06abca80-b85a-11e9-8297-f882e5ce8203.png)
![Screenshot_20190806-143937](https://user-images.githubusercontent.com/53810157/62537822-0ca1ab80-b85a-11e9-82dd-93bcdf878acd.png)
![Screenshot_20190806-143744](https://user-images.githubusercontent.com/53810157/62537829-11665f80-b85a-11e9-8669-c4a3208182d7.png)

**Comment by moovida** [comment]
It is the first icon after the text Geopaparazzi in the toolbar.

**Comment by Mutembeibrian7648** [comment]
Hello Andrea,
I have uploaded the screenshots

**Comment by moovida** [comment]
Yes, it is that icon: 

![image](https://user-images.githubusercontent.com/390250/62538430-15db4a00-b853-11e9-8087-4fb7c9511516.png)

**Comment by Mutembeibrian7648** [comment]
Thank you very much my friend. You have helped a great deal

With Kind Regards

**Comment by moovida** [comment]
Good luck for your quest!
