### ISSUE TITLE
Map View background color

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#617]
Set the Map View background color to white so setting the Opacity of the basemap will lighten the entire map making Project layers easier to see.

Currently opacity will make the basemap purple-ish:
![Screenshot_1565374119](https://user-images.githubusercontent.com/1638313/62799587-73afa200-ba9e-11e9-9251-83a87e531c29.png)

**Comment by moovida** [comment]
Oh yes, that was a leftover of some debugging. Back to white
