### ISSUE TITLE
Editing: duplicate icons

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#622]
Duplicate editing icons are shown.  To reproduce
1.  open map with Spatialite layers shown
2.  press the edit tool (pencil) , three edit tool icons are shown.
3. open layer list, exit layer list back to map 
4. six edit tool icons are shown (three are duplicates)

In step 2 above, I think only one icon (area-select) should be shown, not the select-for-edit icon nor the add point (since an edit layer has not been set).  And really the area-select button should always be available, not just when the edit button is press since it is a view function, not an edit function.

And of course the additional icons in step 4 are a problem as well.  Toggling the edit button will get rid of the extra buttons.

**Comment by brentfraser** [comment]
![Screenshot_1565707074](https://user-images.githubusercontent.com/1638313/62951370-1ae64f00-bda7-11e9-82d2-dc1e3ff000ac.png)

**Comment by moovida** [comment]
The duplication is a bug, thanks.

Regarding the 2 icons, I don't agree. the selection tool with the e inside selects the currently editable layer, opening the attribute table for editing.
Instead the general one allows to select any layer and show information about it.
If that one would not be active, you would need to exit editing mode to be able to query other layers.
What do you think?

**Comment by brentfraser** [comment]
I see your point.  On the other hand, some functions (zoom in, out, layer, etc) as always(-ish) available so it could be the same importance as these.  I consider viewing info on features as super important so the function should always be available.  Especially if labeling is dropped/deferred.

**Comment by moovida** [comment]
Fied
