### ISSUE TITLE
Text label cannot display in spatialite

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [geopaparazzi/geopaparazzi#632]
Text label cannot display in spatialite.
How can I display the label?

**Comment by moovida** [comment]
In the current available from play store there is a labelling option:
http://geopaparazzi.github.io/geopaparazzi/#_spatialite_data_list

In the upcoming version: it is not possible. Issue is discussed in #623

**Comment by sakuya-izayoi-0518** [comment]
moovida
Thanks for ask!!
