### ISSUE TITLE
Force refresh of map/ saving of track

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#633]
We were using geopaparazzi with a detailed aerial image to find the easiest way for a vehicle to pass through dense vegetation in the Australian outback.  The problem was that when zoomed in to level 18 or 19, the current position point on the map moves very fast and there is a need to force a refresh of the map.  The easiest way to do this was to press the forms button on the left of the map, then press the back button beside the home button.  This forced the track to save.  GPAP 5.6.5

Could the functionality of the 'center on GPS button' be extended so that a long press would force the track to save and the screen to be refreshed?

**Comment by AndrewM-** [comment]
I forgot to provide the context.  I was using my phone for navigation through thick vegetation and was turning the screen off to save battery between views.  As geopaparazzi has a north up map, rather than a heads up map, you need to see your track to know which way is forwards.  However when the screen is turned on, the map is displayed but the track is not drawn, hence the need for a means to refresh the track.

**Comment by moovida** [comment]
This will not apply in the upcoming release. I will close it, but let's make sure it doesn't happen. In case reopen please.
