### ISSUE TITLE
Spatialite layers disappear from map when the map is closed

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#634]
Often I would press the back button by accident and close the map view.  The result was that all the loaded spatialite layers that were displayed on the map would be gone when the map was reopened.  Could geoparazzi be made to remember which spatialite layers were displayed when a map is reopened.  

I am also getting to the stage where I want to switch basemaps on the fly without affecting the spatialite data that is displayed.  For example, I want to be able to switch between an aerial view of a forest, which shows the tree tops and a lidar derived hillshade, which shows the features on the ground.  Currently, I can't do this without losing the spatialite overlays.  Gpap 5.6.5

**Comment by moovida** [comment]
Actually this should not have been happening in the older geopaparazzi. But it sure is not happening in the new one. So I will not fix this, but promise that it will work in the upcoming release.
