### ISSUE TITLE
Assign icons and labels to collected form data during field surveys

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#635]
Gpap 5.6.5. Currently I can choose a basic shape and set the size and colour of the shape for spatialite point data but I can't do this for data points that I collect with forms.  I also can only set the label for form data during design time, when I am writing the json form template.  I would love to be able to set different icons for different feature types and would love to be able to turn the labels for a given type of feature on and off.  The basic issue is screen clutter.  I am using a phone and need to avoid using long text labels.  That is why I would like to be able to set icons for each type of survey record and turn labels on and off. 

My favorite icons for this purpose are https://mapicons.mapsmarker.com/category/markers/nature/

**Comment by moovida** [comment]
Hi @AndrewM- , at the time being this is being implemented in smash (more in issue #639 ).
I am afraid this is quite some work to have it in geopaparazzi right now.

**Comment by moovida** [comment]
Closing this here. feel free to reopen it for further discussion.
