### ISSUE TITLE
Map centre/GPS switch default should be GPS 

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#636]
Recording with the switch set the wrong way is a complete disaster.  In general the coordinates in the form should be recorded for the GPS position at the moment the form is opened.  Using a map centre to record a point is relatively rare for me.  For this reason, I think it would be better to default the switch to map centre.  If there is no GPS location, there should be a warning that a location is not available, but the switch should remain at GPS.  It should be a very deliberate decision to use the map centre to record a position.  

In the settings, could we perhaps have an option that returns the switch to GPS after a note is taken and an option that just leaves the switch as the user has set it.  That would ensure that a deliberate decision has to be made for each note, if that is what the user wants.

**Comment by moovida** [comment]
Actually most of it works as you are asking for it.
This is how it works:

* the first time default is GPS. 
* if the GPS doesn't have a fix, the map center is automatically set and the switch is disabled (grayed)
* the switch remembers the last setting the user made

But if there is no fix, the map center is set. And it will be remembered. I only now see that could have been done a bit differently. But it would be some burden to make it "not remember" when the fix imposed the choice.

Feel free to reopen it if in need to discuss this.

**Comment by AndrewM-** [comment]
Thanks for the response.  I have also found that if I open the user forms from the forms button on the main dashboard just after starting Geopaparazzi, the coordinate source is set to *map center* even when the map has never been opened.  I think if a form is opened this way, then *gps position* should be the only option.
