### ISSUE TITLE
Red cross at centre of map is not visible on red backgrounds

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#638]
Lots of places where I work have red soils and the red crosshairs just disappear against the background.  I would be good to be able to select a more visible cross in such circumstances.

**Comment by AndrewM-** [comment]
The red crosshairs are mainly an issue when Geopaparazzi is being used on a mobile phone with a smaller screen size.  The broader strokes in crosshairs shown on tablet screens are more visible.

**Comment by moovida** [comment]
@AndrewM- , in the screen settings there is a way to change the center cross color, width and size. This should solve your problem. Just as an info, I extended the sizes to 1000, so that it works well also on high density screens.

**Comment by AndrewM-** [comment]
Geopaparazzi is pretty big so sometimes I miss things.  Here are a couple of screenshots that show why real examples of cases where the crosshairs could not be seen in outdoor conditions.

![Screenshot_20191116-195359](https://user-images.githubusercontent.com/5060805/69089252-adc41300-0a93-11ea-8d5d-fd500753f8c1.jpg)
![Screenshot_20191117-082015_Geopaparazzi](https://user-images.githubusercontent.com/5060805/69089308-d5b37680-0a93-11ea-9095-15d33ee7855c.jpg)

Will try your recommendations
