### ISSUE TITLE
Could Geopaparazzi make new gpap files in the Geoparazzi folder

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#640]
This is just a minor tidy up request.  I would be happier if new files were created in the application's folder rather than in the parent folder. version 5.6.5.

**Comment by moovida** [comment]
This is actually something that we have been doing for SMASH and are quite happy with it. If there are no objections, I will do that in a the next release.

**Comment by moovida** [comment]
Done for upcoming release.
