### ISSUE TITLE
GPS track is too thick in 6.0.0

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#643]
I had set the text factor high for the previous version of Geopaparazzi, and this issue might be related.

![Screenshot_20191207-132529](https://user-images.githubusercontent.com/5060805/70367874-4a8a0b80-18f0-11ea-9918-4adf2b74387b.jpg)

**Comment by moovida** [comment]
Agreed, changed the initial default from 8 to 4 :-)
