### ISSUE TITLE
The way of move to the center of the background map?

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [geopaparazzi/geopaparazzi#645]
Hello
Has Geopaparazzi 6.X removed the ability to move to the center of the background map? I would like this function to test whether the survey location can be confirmed in advance.

**Comment by moovida** [comment]
What map types are you talking about?
I am current;y adding back **zoom to** for mbtiles, spatialite and geopackage.
Mapsforge map files is a bit harder and might not get in this time.

**Comment by sakuya-izayoi-0518** [comment]
Sorry. I was talking about MBTILES. I'm glad to know when the function returns. Thank you. It is saved in easy-to-understand English. (I am Japanese)

**Comment by moovida** [comment]
Great, then we have it already working. I will release tomorrow I think. There are some issue with spatialite that people need fixed quickly.
