### ISSUE TITLE
Edit Polygon feature has wrong in spatailite db

### ISSUE THREAD

**Issue by skylning** [geopaparazzi/geopaparazzi#652]
Hi, i load a spatilaite polygon layer and enable editing it,i add a polygon feature and saved it,somethimes, the saved geometry position has some offset,such as the picture follow:
![image](https://user-images.githubusercontent.com/3397551/80196484-11102d80-8650-11ea-9e2e-0c9825ee4180.png)
the yellow polygon wa i drawed on map,and the red polygon below the yellow polygon is the saved result.

**Comment by moovida** [comment]
Hi, I have 2 ideas why this might happen (even if it should not):

* the map is not in flat 2D during editing
* a small pan or zoom occurs during editing?

Could you check if it is one of these that makes this happen?

**Comment by skylning** [comment]
@moovida thanks,i test it again,and i found the reason is the map not in flat 2D during editing,and now, how to make the map in flat 2D during editing?

**Comment by moovida** [comment]
Arrrgh, that is a bug then. It is something I will have to check on and fix. In certain situations, the 3d has to be disabled, guess this case slipped through my fingers.

I will use this issuer to update about the fix as soon as I am able to do it.

**Comment by skylning** [comment]
@moovida 
the same bug as polyline editing ,may  be the bug effect all vector layer editing, so hope you can fix it as soon,or  give some suggestion to disabled 3d map.thanks.

**Comment by moovida** [comment]
closed via #653
