### ISSUE TITLE
Search layer option

### ISSUE THREAD

**Issue by Comiii** [geopaparazzi/geopaparazzi#654]
Hi, is there are the way to search layers from app?

**Comment by moovida** [comment]
Hi @Comiii , I am not sure what you mean here? Can you explain?

**Comment by Comiii** [comment]
Hi @moovida , Let say that I have layer Cadastral parcels and that I want to find parcel with number 4312  , and when I select it that it show on the map.

**Comment by moovida** [comment]
Ahh, now I see @Comiii . It sounds like a useful feature.
But I am sorry at the current time it is not possible to do so. :-/
